"""CIRCUIT-1 lot 1.1 — LE REGISTRE DES CHIFFRES : chaque chiffre servi par LABUSE est déclaré
ICI, une fois — id (snake_case, ceux de l'inventaire CIRCUIT-0 conservés), libellé d'écran,
unité, niveau, définition en français (dénominateur et fenêtre compris), moteur (ids de
moteurs.csv), fonction (référence du producteur — fichier:fonction ; devient un chemin Python
importable au fil du lot 2.5 quand les SQL propres sont extraites), réservoirs (ids de
reservoirs.csv), portée (`run` = ne change qu'à la bascule · `live` = change à l'injection).

Le code est LA vérité ; la base (`registre_*`, cf. sync.py) n'en est que le miroir servi à la
page Circuit et à la sonde. Un chiffre absent d'ici n'a pas le droit d'exister à l'écran
(garde de couverture : tests/test_registre.py).
"""
from __future__ import annotations

from dataclasses import dataclass, field

VERSION_DEF = "2026-09-05"      # date de la définition courante (bump à chaque changement de sens)


@dataclass(frozen=True)
class Chiffre:
    libelle: str
    unite: str          # % · € · €/m² · m² · logements · classe · verdict · tranche · date · nombre
    niveau: str         # parcelle · commune · zone · proprietaire · annonce · global
    definition: str     # une phrase, dénominateur et fenêtre compris
    moteur: str | None  # id de moteurs.csv, None si sql_propre/passe_plat/constante/front
    calcul: str         # moteur · sql_propre · passe_plat · constante · front (front → à rapatrier, lot 2.4)
    fonction: str       # référence du producteur (fichier:fonction) — appelable au fil du lot 2.5
    reservoirs: tuple[str, ...] = field(default_factory=tuple)   # ids reservoirs.csv ; vide = interne
    portee: str = "live"        # run | live
    version_def: str = VERSION_DEF


C = Chiffre

CHIFFRES: dict[str, Chiffre] = {
 "tier_opportunite": C("Verdict · Classement servi", "classe", "parcelle",
    "tier du run servi (brûlante→froide), reconstruit à la bascule",
    moteur="scoring_p_v2", calcul="moteur", fonction="src/labuse/cli.py (build-mvt) ; parcel_flags",
    reservoirs=("bd_topo", "cosia", "dvf", "filosofi_carreaux", "sitadel",), portee="run"),
 "zone_plu_famille": C("Zonage PLU (par type)", "classe", "parcelle",
    "famille de zone (U/AU/A/N) portée par parcel_zone_plu, une zone par parcelle",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/app.py:map_layers_geojson (parcel_zone_plu)",
    reservoirs=("gpu_plu_api_carto",), portee="live"),
 "tranche_prix_vefa": C("Prix du logement neuf (VEFA)", "tranche", "commune",
    "tranche de prix médian VEFA 36 mois glissants, ≥10 ventes avec prix sinon hachure",
    moteur="marche_communes", calcul="moteur", fonction="src/labuse/ingestion/vefa_neuf.py:118",
    reservoirs=("dvf", "sitadel",), portee="live"),
 "classe_residuel": C("Densifier l'existant", "classe", "parcelle",
    "classe de sous-densité issue de la vue parcel_residuel (run résiduel servi)",
    moteur="residuel", calcul="moteur", fonction="src/labuse/faisabilite/residuel.py:80",
    reservoirs=("bd_topo", "cadastre_api_carto", "cosia",), portee="run"),
 "surface_parcelle_m2": C("Surface", "m²", "parcelle",
    "surface cadastrale parcels.surface_m2",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/modules.py:scoreur_adresse",
    reservoirs=("cadastre_api_carto",), portee="live"),
 "capacite_logements": C("Capacité (logements)", "logements", "parcelle",
    "capacité estimée depuis SDP résiduelle / taille moyenne logement",
    moteur="residuel", calcul="moteur", fonction="src/labuse/api/modules.py:faisabilite_sens1",
    reservoirs=("bd_topo", "cosia", "gpu_plu_api_carto",), portee="run"),
 "sdp_residuelle_m2": C("SDP résiduelle", "m²", "parcelle",
    "max(0, SDP_max − SDP_existante)",
    moteur="residuel", calcul="moteur", fonction="src/labuse/faisabilite/residuel.py:80",
    reservoirs=("cosia", "gpu_plu_api_carto",), portee="run"),
 "charge_fonciere_eur": C("Charge foncière", "€", "parcelle",
    "prix de sortie × SDP − coûts − marge (bilan à rebours)",
    moteur="bilan_promoteur", calcul="moteur", fonction="src/labuse/faisabilite/bilan.py",
    reservoirs=("cadastre_api_carto", "dvf",), portee="live"),
 "taxe_amenagement_eur": C("Taxe d'aménagement", "€", "parcelle",
    "calcul ligne-à-ligne, taux communal SAISI obligatoire, jamais un défaut",
    moteur="taxe_amenagement", calcul="moteur", fonction="src/labuse/taxe_amenagement.py",
    reservoirs=(), portee="live"),
 "n_vigilances": C("Vigilances", "nombre", "parcelle",
    "compte des couches cascade en SOFT_FLAG/HARD_EXCLUDE",
    moteur="cascade", calcul="moteur", fonction="src/labuse/api/modules.py:risques_audit",
    reservoirs=("abf_merimee", "deal_ppr", "georisques_api", "znieff_inpn",), portee="run"),
 "n_extraits_plu": C("extraits (règlement)", "nombre", "commune",
    "extraits de règlement servis par commune (corpus)",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/modules.py:1893-1952",
    reservoirs=("gpu_plu_api_carto", "sudocuh",), portee="live"),
 "n_communes_rnu": C("au RNU", "nombre", "global",
    "communes au statut rnu du corpus (registre config/rnu_communes.yaml)",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/modules.py:1942",
    reservoirs=("sudocuh",), portee="live"),
 "simulplu_resultat": C("Simuler un changement (parcelles gagnées)", "nombre", "commune",
    "re-verdict cascade sous zonage hypothétique (dryrun)",
    moteur="cascade", calcul="moteur", fonction="src/labuse/api/moteurs.py:56-124",
    reservoirs=("gpu_plu_api_carto",), portee="run"),
 "comparateur_composite": C("Score composite", "nombre", "commune",
    "moyenne pondérée min-max des 6 axes présents, poids réglables",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/comparateur.py:88-118",
    reservoirs=("cosia", "dvf", "sitadel",), portee="run"),
 "stock_opportunites": C("Stock d'opportunités (brûlantes + chaudes)", "nombre", "commune",
    "count tiers brûlante+chaude au run servi, par insee",
    moteur="scoring_p_v2", calcul="moteur", fonction="src/labuse/api/comparateur.py:47-50",
    reservoirs=("cosia", "dvf", "sitadel",), portee="run"),
 "velocite_delai_median_mois": C("Vélocité admin (délai médian dépôt→autorisation, mois)", "nombre", "commune",
    "percentile_cont(0.5) sur m10_permit_delais famille logements",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/comparateur.py:51-53",
    reservoirs=("sitadel",), portee="live"),
 "permis_5a_n": C("Dynamisme permis (SITADEL, 5 ans)", "nombre", "commune",
    "count sitadel_permits date ≥ now−5 ans",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/comparateur.py:54-56",
    reservoirs=("sitadel",), portee="live"),
 "deficit_sru_pts": C("Déficit SRU (objectif − taux LLS, points)", "nombre", "commune",
    "greatest(objectif_pct − taux_lls, 0) depuis commune_contexte_sru",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/comparateur.py:56",
    reservoirs=("sru_dhup",), portee="live"),
 "pression_zan_ha": C("Pression ZAN (ENAF consommé 2021-2024, ha)", "nombre", "commune",
    "conso_2021_2024_m2 / 10000",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/comparateur.py:57",
    reservoirs=(), portee="live"),
 "prix_neuf_vefa_eur_m2": C("Prix de sortie neuf VEFA (DVF, €/m²)", "€/m²", "commune",
    "médiane VEFA live, MÊME moteur que fiche et carte (divergence précalc corrigée)",
    moteur="marche_communes", calcul="moteur", fonction="src/labuse/api/comparateur.py:139-141 (neuf_vefa_commune LIVE — RETOURS-11F M1)",
    reservoirs=("dvf",), portee="live"),
 "prix_ancien_median_eur_m2": C("€/m² ancien", "€/m²", "commune",
    "médiane DVF ventes strictes, filtre de retenue du baromètre",
    moteur="marche_communes", calcul="moteur", fonction="src/labuse/api/moteurs.py:prix_ancien_communes (partagé PDF baromètre)",
    reservoirs=("dvf",), portee="live"),
 "n_parcelles_pm": C("Parcelles détenues", "nombre", "proprietaire",
    "count parcelle_personne_morale par SIREN (millésime 2025)",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/modules.py:patrimoine",
    reservoirs=("dgfip_parcelles_pm",), portee="live"),
 "prod_spec_kwh_kwc": C("Productible", "nombre", "parcelle",
    "productible PVGIS SARAH3 gelé au run du builder (parcel_solar)",
    moteur="solaire", calcul="moteur", fonction="src/labuse/api/modules.py:prospection_solaire",
    reservoirs=("bd_topo", "pvgis",), portee="run"),
 "azimut_bati_deg": C("Azimut (Estimé)", "nombre", "parcelle",
    "azimut du bâti principal, Estimé",
    moteur="solaire", calcul="moteur", fonction="src/labuse/ingestion/solaire.py (ST_OrientedEnvelope)",
    reservoirs=("bd_topo",), portee="run"),
 "n_piscines": C("Piscines détectées", "nombre", "commune",
    "count parcel_equipements piscine (BD ORTHO 2025, ~90,7 %)",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/modules.py:prospection_piscines",
    reservoirs=("bd_ortho",), portee="live"),
 "mutations_12m_n": C("Mutations 12 mois", "nombre", "commune",
    "count dvf_mutations sur les 12 derniers mois DE DONNÉES (pas calendaire)",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/app.py:1934-1940",
    reservoirs=("dvf",), portee="live"),
 "acquisitions_pm_n": C("Acquisitions récentes (PM)", "nombre", "commune",
    "diff CONSTAT entre millésimes PM, maille commune",
    moteur="proprietaire_historique", calcul="moteur", fonction="src/labuse/api/app.py:commune_acquisitions_pm",
    reservoirs=("dgfip_parcelles_pm",), portee="live"),
 "permis_12m_n": C("Permis (12 mois)", "nombre", "commune",
    "count sitadel_permits fenêtre 12 mois",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/modules.py:permis",
    reservoirs=("sitadel",), portee="live"),
 "point_mort_n": C("Permis au point mort", "nombre", "commune",
    "permis autorisés sans DOC/DAACT dans la fenêtre",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/modules.py:promesses",
    reservoirs=("sitadel",), portee="live"),
 "n_densifiables": C("Parcelles densifiables", "nombre", "commune",
    "count parcel_renouvellement au run servi",
    moteur="renouvellement", calcul="moteur", fonction="src/labuse/api/modules.py:renouvellement",
    reservoirs=(), portee="run"),
 "population_zone": C("Habitants (zone)", "nombre", "zone",
    "somme carreaux Filosofi 200 m intersectant l'isochrone",
    moteur="zone", calcul="moteur", fonction="src/labuse/zone.py (population_zone — point Filosofi UNIQUE)",
    reservoirs=("filosofi_carreaux",), portee="live"),
 "n_concurrents_zone": C("Concurrents (NAF)", "nombre", "zone",
    "count sirene_etablissements du NAF choisi dans la zone, chacun avec son temps",
    moteur="zone", calcul="moteur", fonction="src/labuse/zone.py (comptages_zone)",
    reservoirs=("sirene_etablissements",), portee="live"),
 "emplois_fourchette": C("Emplois (fourchette)", "tranche", "zone",
    "somme des tranches d'effectifs SIRENE (jamais un point)",
    moteur="zone", calcul="moteur", fonction="src/labuse/zone.py",
    reservoirs=("sirene_etablissements",), portee="live"),
 "revenu_approche_eur": C("Revenu (valeur approchée)", "€", "zone",
    "niveau de vie approché N/M carreaux couverts (i_est_200)",
    moteur="zone", calcul="moteur", fonction="src/labuse/zone.py",
    reservoirs=("filosofi_carreaux",), portee="live"),
 "trafic_mja": C("Trafic (MJA)", "nombre", "zone",
    "comptage MJA du tronçon RN le plus proche, millésime porté par tronçon",
    moteur=None, calcul="passe_plat", fonction="src/labuse/zone.py",
    reservoirs=("trafic_rn",), portee="live"),
 "annonces_actives_n": C("Biens en vente", "nombre", "commune",
    "count pige_biens actifs a_qualifier=false ; n<5 → NULL insuffisant",
    moteur="marche_pige", calcul="moteur", fonction="src/labuse/pige/marche.py:71-91",
    reservoirs=("radar_pige",), portee="live"),
 "prix_demande_median_eur_m2": C("Prix demandé (médiane)", "€/m²", "commune",
    "médiane des prix affichés terrain/bâti, n<5 masqué",
    moteur="marche_pige", calcul="moteur", fonction="src/labuse/pige/marche.py:71-91",
    reservoirs=("radar_pige",), portee="live"),
 "delai_vente_median_j": C("Délai médian", "nombre", "commune",
    "médiane 1re vue → retrait/vente",
    moteur="marche_pige", calcul="moteur", fonction="src/labuse/pige/marche.py",
    reservoirs=("radar_pige",), portee="live"),
 "ecart_demande_acte_pct": C("Écart demandé/acté", "%", "commune",
    "médiane demandé vs médiane DVF actée, servi dès SEUIL_N biens",
    moteur="marche_pige", calcul="moteur", fonction="src/labuse/api/fiche_commune.py:16-58 (comparable, partagé)",
    reservoirs=("dvf", "radar_pige",), portee="live"),
 "rang_tier": C("Rang (dans le tier)", "nombre", "parcelle",
    "rang au sein du tier",
    moteur="scoring_p_v2", calcul="moteur", fonction="src/labuse/api/app.py:3283",
    reservoirs=(), portee="run"),
 "prix_terrain_secteur_eur_m2": C("Terrain nu secteur", "€/m²", "parcelle",
    "médiane DVF rayon adaptatif 500→1500 m, trim 5 %, min 8 ventes, indice fiabilité",
    moteur="sector_price", calcul="moteur", fonction="src/labuse/faisabilite/bilan.py (sector_price)",
    reservoirs=("cadastre_api_carto", "dvf",), portee="live"),
 "prix_sortie_bati_eur_m2": C("Prix de sortie — bâti secteur", "€/m²", "parcelle",
    "médiane bâti secteur + tendance calculées côté front sur ventes serveur (Q5.4)",
    moteur="sector_price", calcul="moteur", fonction="frontend/src/components/fiche/marche.tsx:19-90",
    reservoirs=("dvf",), portee="live"),
 "ventes_100m_n": C("Ventes à moins de 100 m", "nombre", "parcelle",
    "count mutations à <100 m + médiane",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/app.py:3283 (dvf_parcelle)",
    reservoirs=("dvf",), portee="live"),
 "pente_deg": C("Pente", "nombre", "parcelle",
    "pente moyenne parcelle (RGE ALTI), flag terrassement",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/app.py:3283 (viabilisation)",
    reservoirs=("rge_alti",), portee="live"),
 "piscine_m2": C("Piscine ~m²", "m²", "parcelle",
    "surface détectée parcel_equipements (BD ORTHO 2025)",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/app.py:3283",
    reservoirs=("bd_ortho",), portee="live"),
 "distance_arret_m": C("Transport public — au plus proche", "m", "parcelle",
    "plus proche arrêt/pôle (distance en m)",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/app.py:3283 (proximites)",
    reservoirs=("gtfs_pan", "osm_transport",), portee="live"),
 "n_permis_proximite": C("Permis à proximité", "nombre", "parcelle",
    "permis Sitadel dans le rayon, avec distance et date",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/app.py:3283",
    reservoirs=("sitadel",), portee="live"),
 "depots_secteur_n": C("Déposés/autorisés (Sitadel)", "nombre", "zone",
    "activité de dépôt par année dans le secteur",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/app.py:3283",
    reservoirs=("sitadel",), portee="live"),
 "type_proprietaire": C("Propriétaire (type)", "classe", "proprietaire",
    "personne morale (dénomination) / personne physique non recensée — millésime 2025",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/app.py:3283 (proprietaire_moral)",
    reservoirs=("dgfip_parcelles_pm",), portee="live"),
 "verdict_icd": C("Confiance données", "verdict", "parcelle",
    "verdict de complétude des couches + liste des manquants",
    moteur="cascade", calcul="moteur", fonction="src/labuse/api/app.py:3283 (bloc icd)",
    reservoirs=(), portee="run"),
 "divisible_classe": C("Division (candidate)", "classe", "parcelle",
    "présence dans division_or_candidates — run figé q_v10, workflow de revue",
    moteur="division_or", calcul="moteur", fonction="src/labuse/api/app.py:2692-2696",
    reservoirs=("cadastre_api_carto", "cosia", "gpu_plu_api_carto",), portee="run"),
 "statut_plu": C("Règles d'urbanisme (statut)", "classe", "commune",
    "RNU (registre) l'emporte ; sinon statut du registre veille_plu",
    moteur="plu_destinations", calcul="moteur", fonction="src/labuse/api/fiche_commune.py:137-144",
    reservoirs=("gpu_plu_api_carto", "sudocuh",), portee="live"),
 "zan_reste_ha": C("Enveloppe ZAN (reste)", "nombre", "commune",
    "enveloppe restante estimée depuis conso ENAF",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/fiche_commune.py (rarete)",
    reservoirs=(), portee="live"),
 "taux_lls_pct": C("Taux LLS", "%", "commune",
    "taux LLS de l'inventaire SRU",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/fiche_commune.py (commune_contexte_sru)",
    reservoirs=("sru_dhup",), portee="live"),
 "plh_objectif_logements_an": C("Objectif logements/an", "logements", "commune",
    "objectif PLH, chaque chiffre porte sa référence doc+page",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/fiche_commune.py (plh_epci)",
    reservoirs=("plh_epci",), portee="live"),
 "prix_terrain_zone_eur_m2": C("Terrain nu (zone U / AU)", "€/m²", "commune",
    "médiane DVF terrain nu par famille de zone, seuil 10 ventes",
    moteur="marche_communes", calcul="moteur", fonction="src/labuse/faisabilite/marche_commune.py (ligne2_terrain_zone)",
    reservoirs=("dvf", "gpu_plu_api_carto",), portee="live"),
 "loyer_median_eur_m2": C("Loyer médian", "€/m²", "commune",
    "estimation locative loyers.py — entrées à confirmer (DOUTE)",
    moteur="loyers", calcul="moteur", fonction="src/labuse/api/fiche_commune.py (loyer)",
    reservoirs=(), portee="live"),
 "n_parcelles_commune": C("N parcelles", "nombre", "commune",
    "count parcels par commune",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/app.py:1905",
    reservoirs=("cadastre_api_carto",), portee="live"),
 "part_zone_U_pct": C("Zonage — U", "%", "commune",
    "surface cadastrée U / surface zonée totale (somme=100 %)",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/app.py:1908-1955 (_foncier_commune, PART DE SURFACE)",
    reservoirs=("cadastre_api_carto", "gpu_plu_api_carto",), portee="live"),
 "part_zone_AU_pct": C("Zonage — AU", "%", "commune",
    "surface AU / surface zonée",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/app.py:1908-1955",
    reservoirs=("cadastre_api_carto", "gpu_plu_api_carto",), portee="live"),
 "part_zone_A_pct": C("Zonage — A", "%", "commune",
    "surface A / surface zonée (Saint-Paul : 35,8 % — la part en PARCELLES vaut 17,8 %)",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/app.py:1908-1955",
    reservoirs=("cadastre_api_carto", "gpu_plu_api_carto",), portee="live"),
 "part_zone_N_pct": C("Zonage — N", "%", "commune",
    "surface N / surface zonée (Saint-Paul : 47,2 % — la part en PARCELLES vaut 6,8 %)",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/app.py:1908-1955",
    reservoirs=("cadastre_api_carto", "gpu_plu_api_carto",), portee="live"),
 "ppr_pct": C("PPR (part des parcelles)", "%", "commune",
    "part des parcelles de la commune intersectant la couche ppr",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/fiche_commune.py:66-88 (_pct_layer)",
    reservoirs=("deal_ppr",), portee="live"),
 "catnat_n": C("Arrêtés CatNat", "nombre", "commune",
    "count catnat_arretes",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/fiche_commune.py",
    reservoirs=(), portee="live"),
 "habitants_n": C("Habitants", "nombre", "commune",
    "population INSEE/Filosofi commune",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/fiche_commune.py:123 (population)",
    reservoirs=("filosofi_carreaux", "insee_rp_logement",), portee="live"),
 "vacance_pct": C("Vacance", "%", "commune",
    "100 × vacants / logements (RP)",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/fiche_commune.py:123",
    reservoirs=("insee_rp_logement",), portee="live"),
 "qpv_n": C("QPV", "nombre", "commune",
    "count QPV intersectant la commune",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/fiche_commune.py",
    reservoirs=("qpv_2024",), portee="live"),
 "prix_demande_eur": C("Prix demandé", "€", "annonce",
    "fait déclaré de l'annonce (pige_faits), jamais le texte",
    moteur=None, calcul="passe_plat", fonction="src/labuse/pige/client.py",
    reservoirs=("radar_pige",), portee="live"),
 "copilote_compte_parcelles": C("Compte de parcelles (réponse)", "nombre", "global",
    "MÊME facette canonique que le filtre écran (égalité verrouillée)",
    moteur=None, calcul="sql_propre", fonction="src/labuse/copilote_v2/outils.py:130-219",
    reservoirs=("cadastre_api_carto",), portee="run"),
 "destination_statut": C("Peut-on ouvrir une activité ? (verdict)", "verdict", "parcelle",
    "MÊME moteur plu.destinations que fiche et étude de zone",
    moteur="plu_destinations", calcul="moteur", fonction="src/labuse/copilote_v2/outils.py:573-599",
    reservoirs=("gpu_plu_api_carto", "sudocuh",), portee="live"),
 "n_veilles": C("Veilles actives", "nombre", "global",
    "count veilles du compte",
    moteur=None, calcul="sql_propre", fonction="src/labuse/copilote_v2/veilles.py:82-88",
    reservoirs=(), portee="live"),
 "projet_cadrage_n": C("Parcelles (cadrage)", "nombre", "global",
    "count parcelles du projet",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/projets.py:606-640",
    reservoirs=(), portee="run"),
 "projet_retenues_n": C("Retenues", "nombre", "global",
    "count retenues",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/projets.py:606-640",
    reservoirs=(), portee="run"),
 "crm_cartes_n": C("Cartes par colonne", "nombre", "global",
    "count par colonne",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/crm_columns.py:34",
    reservoirs=(), portee="live"),
 "n_notifications": C("Notifications non lues", "nombre", "global",
    "count event_log non lus du compte",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/events.py:696",
    reservoirs=(), portee="live"),
 "n_bascules_7j": C("Bascules (7 jours)", "nombre", "global",
    "bascules de tier détectées vs run précédent",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/events.py:1086-1153",
    reservoirs=(), portee="run"),
 "n_biens_du_jour": C("Biens du jour (digest)", "nombre", "global",
    "biens validés du jour, cartes HTML plafond 10 + « et N autres »",
    moteur="marche_pige", calcul="moteur", fonction="src/labuse/api/events.py:1160-1216",
    reservoirs=("radar_pige",), portee="live"),
 "n_biens_veille": C("NB_BIENS (Brevo 13)", "nombre", "global",
    "len(matches) de LA veille — un mail par veille",
    moteur="marche_pige", calcul="moteur", fonction="src/labuse/pige/digests.py:303-313",
    reservoirs=("radar_pige",), portee="live"),
 "n_parcelles_ile": C("Parcelles (accueil)", "nombre", "global",
    "count parcels mesuré, jamais en dur",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/accueil.py:57",
    reservoirs=("cadastre_api_carto",), portee="live"),
 "n_sources": C("Sources (accueil)", "nombre", "global",
    "count des sources AFFICHÉES (66 au 05/09)",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/accueil.py:57 (WHERE_AFFICHEES)",
    reservoirs=(), portee="live"),
 "run_label_servi": C("Run servi (pied)", "classe", "global",
    "label du run servi",
    moteur=None, calcul="constante", fonction="src/labuse/api/accueil.py:57",
    reservoirs=(), portee="run"),
 "prix_flash_eur": C("Rapport Flash — 79 €", "€", "global",
    "prix de l'offre Flash, source unique offres.py",
    moteur=None, calcul="constante", fonction="src/labuse/offres.py (source unique des prix)",
    reservoirs=(), portee="live"),
 "n_a_faire": C("À faire (pilotage)", "nombre", "global",
    "gestes attendus : nouvelle_version + a_rafraichir (arbitre unique etats_sources)",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/dashboard.py:250",
    reservoirs=(), portee="live"),
 "n_sources_surveillees": C("sous veille (écran Circuit)", "nombre", "global",
    "49 = lignes source_veille actives à vraie sonde, compte brut",
    moteur=None, calcul="sql_propre", fonction="src/labuse/flux.py:199-201",
    reservoirs=(), portee="live"),
 "ecart_candidat_pct": C("Écart candidat vs servi", "%", "global",
    "comparaison distribution tiers candidat/servi",
    moteur=None, calcul="sql_propre", fonction="src/labuse/golden_ops.py:33-60 (_DISTRIB_CACHE)",
    reservoirs=(), portee="run"),
 "ia_cout_eur": C("Conso IA (€)", "€", "global",
    "somme cout par modèle/surface 30 j (ledger ia_log)",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/dashboard.py:721",
    reservoirs=(), portee="live"),
 "n_depots_a_verifier": C("Dépôts à vérifier", "nombre", "global",
    "count pige_depots en attente de validation",
    moteur=None, calcul="sql_propre", fonction="src/labuse/pige/api.py (a_verifier)",
    reservoirs=("radar_pige",), portee="live"),
 "n_comptes_actifs": C("Comptes actifs", "nombre", "global",
    "count comptes par statut",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/dashboard.py:462",
    reservoirs=(), portee="live"), # ── longue traîne (lot 1.3) — robinets à zéro de l'inventaire, chiffres déclarés ici ──
 "n_procedures_plu": C("Procédures d'urbanisme (en cours)", "nombre", "commune",
    "compte des procédures PLU non réconciliées (révision/élaboration) du registre veille_plu",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/moteurs.py:simulplu_procedures",
    reservoirs=("sudocuh",), portee="live"),
 "assemblage_parcelles_n": C("Parcelles assemblées", "nombre", "parcelle",
    "compte des parcelles retenues dans l'assemblage courant",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/moteurs.py:moteurs_assemblage",
    reservoirs=("cadastre_api_carto",), portee="live"),
 "assemblage_surface_m2": C("Surface assemblée", "m²", "parcelle",
    "somme des surfaces cadastrales des parcelles de l'assemblage",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/moteurs.py:moteurs_assemblage",
    reservoirs=("cadastre_api_carto",), portee="live"),
 "courrier_demandes_n": C("Courriers demandés", "nombre", "global",
    "compte des demandes de courrier propriétaire du compte",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/modules.py:courriers",
    reservoirs=(), portee="live"),
 "annee_ortho": C("Année de la photographie aérienne", "date", "global",
    "millésime du fond ortho affiché (registre ORTHO_YEARS)",
    moteur=None, calcul="constante", fonction="frontend/src/components/map/basemaps.ts (ORTHO_YEARS)",
    reservoirs=("bd_ortho",), portee="live"),
 "pipeline_entrees_n": C("Entrées du pipeline", "nombre", "global",
    "compte des entrées du pipeline (retour terrain) par statut, périmètre du compte",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/app.py:2250 (pipeline_entries)",
    reservoirs=(), portee="live"),
 "couverture_commune_pct": C("Couverture des sources par commune", "%", "commune",
    "part des communes couvertes par chaque source (taux d'ingestion)",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/app.py:1055",
    reservoirs=(), portee="live"),
 "usage_outil_n": C("Usage des outils (30 j)", "nombre", "global",
    "compte d'événements d'usage par outil sur la fenêtre choisie (7/30/90 j)",
    moteur=None, calcul="sql_propre", fonction="src/labuse/api/dashboard.py:1450",
    reservoirs=(), portee="live"),
}
