"""CIRCUIT-2 lot 1.1 — LE REGISTRE DES DONNÉES (ex-registre des chiffres, CIRCUIT-1 1.1) :
TOUT ce qui s'affiche et vient d'une source est déclaré ICI, une fois — pas seulement les
nombres. Chaque donnée porte son `type` (nombre · classe · texte · liste · geometrie · couche),
les champs de CIRCUIT-1 (définition, moteur ou passe-plat, réservoirs, portée, version), et
selon le type : le DOMAINE d'une classe (valeurs possibles + leur source), la TABLE ou le
TUILAGE d'une couche/géométrie et sa FABRICATION (`build-mvt`, `geom_simple`, vue, requête,
WMTS distant).

Portées : `run` (ne change qu'à la bascule) · `live` (change à l'injection) · `projet`
(saisie client, pas de réservoir, tampon « saisi par le client le … » — 0-bis).
États (règle 4 du mandat) : une donnée non numérique est `servie`, « non déterminée » (la
source ne dit pas) ou « non calculée » (la chaîne a échoué) — l'état voyage dans la Valeur,
jamais un échec déguisé en absence.

`en_attente` : donnée DÉCLARÉE dont le réservoir ou l'affichage arrive par un chantier nommé
(1.8 — maquettes d'exports, réglementaires CIRCUIT-3) ; elle n'est servie par AUCUN robinet
tant que le champ est posé (verrouillé par test), et ce n'est PAS une exception au registre :
rien ne s'affiche hors registre.

Le code est LA vérité ; la base (`registre_*`, cf. sync.py) n'en est que le miroir servi à la
page Circuit et à la sonde. Une donnée absente d'ici n'a pas le droit d'exister à l'écran
(garde de couverture : tests/test_registre.py, tests/test_circuit2_lot1.py).
"""
from __future__ import annotations

from dataclasses import dataclass, field, replace

VERSION_DEF = "2026-09-05"      # date de la définition courante (bump à chaque changement de sens)

TYPES = ("nombre", "classe", "texte", "liste", "geometrie", "couche")

#: type dérivé de l'unité quand la déclaration ne le pose pas explicitement (`type="auto"`)
_TYPE_PAR_UNITE = {"classe": "classe", "verdict": "texte", "tranche": "classe", "date": "texte"}


@dataclass(frozen=True)
class Donnee:
    libelle: str
    unite: str          # % · € · €/m² · m² · logements · classe · verdict · tranche · date · nombre · m
    niveau: str         # parcelle · commune · zone · proprietaire · annonce · global
    definition: str     # une phrase, dénominateur et fenêtre compris
    moteur: str | None  # id de moteurs.csv, None si sql_propre/passe_plat/constante/front
    calcul: str         # moteur · sql_propre · passe_plat · constante · front (front → à rapatrier)
    fonction: str       # référence du producteur (fichier:fonction)
    reservoirs: tuple[str, ...] = field(default_factory=tuple)   # ids reservoirs.csv ; vide = interne
    portee: str = "live"        # run | live | projet
    version_def: str = VERSION_DEF
    type: str = "auto"          # ∈ TYPES ; "auto" → dérivé de l'unité (_TYPE_PAR_UNITE)
    domaine: tuple[str, ...] | None = None    # classe : les valeurs possibles
    domaine_source: str | None = None         # classe : la source du domaine (GPU, arrêté, PPR…)
    table: str | None = None    # couche/géométrie/passe-plat : la table (ou le tuilage) lue
    fabrication: str | None = None   # couche : build-mvt · geom_simple · vue · requete · wmts_distant
    en_attente: str | None = None    # déclarée, pas encore servie — le chantier qui l'apporte


#: rétro-compatibilité CIRCUIT-1 (alias conservés — 1.1 : « ne rien casser »)
Chiffre = Donnee
C = Donnee

DONNEES: dict[str, Donnee] = {
 "tier_opportunite": C("Verdict · Classement servi", "classe", "parcelle",
    "tier du run servi (brûlante→froide), reconstruit à la bascule",
    moteur="scoring_p_v2", calcul="moteur", fonction="src/labuse/cli.py (build-mvt) ; parcel_flags",
    reservoirs=("bd_topo", "cosia", "dvf", "filosofi_carreaux", "sitadel",), portee="run",
    domaine=("brulante", "chaude", "a_creuser", "reserve_fonciere", "ecartee"),
    domaine_source="tiers du scoring P v2 (scoring/p_v2/statuts.py)"),
 "zone_plu_famille": C("Zonage PLU (par type)", "classe", "parcelle",
    "famille (U/AU/A/N) de la zone DOMINANTE par surface de la parcelle (drapeau a_cheval, "
    "zone_parts servies) — moteur zone_servie (ZONE-1) ; ≠ zonage_commune (parts d'une commune)",
    moteur="zone_servie", calcul="moteur",
    fonction="src/labuse/faisabilite/zone_servie.py:zone_dominante",
    reservoirs=("gpu_plu_api_carto",), portee="live",
    domaine=("U", "AU", "A", "N"),
    domaine_source="familles de zones du GPU (Géoportail de l'urbanisme)"),
 "tranche_prix_vefa": C("Prix du logement neuf (VEFA)", "tranche", "commune",
    "tranche de prix médian VEFA 36 mois glissants, ≥10 ventes avec prix sinon hachure",
    moteur="marche_service", calcul="moteur", fonction="src/labuse/ingestion/vefa_neuf.py:118",
    reservoirs=("dvf", "sitadel",), portee="live",
    domaine=("moins_4000", "4000_4500", "4500_5000", "5000_5500", "5500_plus", "sous_seuil"),
    domaine_source="tranches TRANCHE_LIBELLE (ingestion/vefa_neuf.py)"),
 "classe_residuel": C("Densifier l'existant", "classe", "parcelle",
    "classe de sous-densité du run résiduel servi, lue SOUS la garde de zone dominante "
    "(bloc au sol du moteur potentiel — EXPORTS-1 lot 3)",
    moteur="potentiel", calcul="moteur",
    fonction="src/labuse/faisabilite/potentiel.py:bloc_potentiel (au_sol, garde zone_servie)",
    reservoirs=("bd_topo", "cadastre_api_carto", "cosia",), portee="run",
    domaine=("sous_densite", "dense"), domaine_source="parcel_residuel.sous_densite (seuil des hypothèses de bilan)"),
 "surface_parcelle_m2": C("Surface", "m²", "parcelle",
    "surface cadastrale parcels.surface_m2",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/scoreur.py:scoreur_adresse",
    reservoirs=("cadastre_api_carto",), portee="live", table="parcels.surface_m2"),
 "capacite_logements": C("Capacité (logements)", "logements", "parcelle",
    "logements estimés du scénario table rase (après plafond de densité et stationnement) — "
    "bloc potentiel (EXPORTS-1 lot 3)",
    moteur="potentiel", calcul="moteur",
    fonction="src/labuse/faisabilite/potentiel.py:bloc_potentiel (table_rase.logements)",
    reservoirs=("bd_topo", "cosia", "gpu_plu_api_carto",), portee="run"),
 "sdp_residuelle_m2": C("SDP résiduelle", "m²", "parcelle",
    "max(0, SDP_max − SDP_existante) du run servi, sous garde de lecture zone dominante "
    "(A/N → 0 avec cause dite — ZONE-1)",
    moteur="potentiel", calcul="moteur",
    fonction="src/labuse/faisabilite/potentiel.py:bloc_potentiel (au_sol.sdp_residuelle_m2)",
    reservoirs=("cosia", "gpu_plu_api_carto",), portee="run"),
 "potentiel_verdict": C("Potentiel (verdict)", "verdict", "parcelle",
    "phrase composée du bloc « au sol / en hauteur / table rase » (moteur potentiel) — "
    "jamais un bloc creux (section omise si rien d'évaluable)",
    moteur="potentiel", calcul="moteur",
    fonction="src/labuse/faisabilite/potentiel.py:bloc_potentiel (verdict)",
    reservoirs=("bd_topo", "cosia", "gpu_plu_api_carto",), portee="run"),
 "charge_fonciere_eur": C("Charge foncière", "€", "parcelle",
    "prix de sortie × SDP − coûts − marge (bilan à rebours)",
    moteur="bilan_promoteur", calcul="moteur", fonction="src/labuse/faisabilite/bilan.py",
    reservoirs=("cadastre_api_carto", "dvf",), portee="live"),
 "taxe_amenagement_eur": C("Taxe d'aménagement", "€", "parcelle",
    "calcul ligne-à-ligne, taux communal SAISI obligatoire, jamais un défaut",
    moteur="taxe_amenagement", calcul="moteur", fonction="src/labuse/taxe_amenagement.py",
    reservoirs=(), portee="live"),
 "n_vigilances": C("Vigilances", "nombre", "parcelle",
    "compte des couches cascade en SOFT_FLAG/HARD_EXCLUDE",
    moteur="cascade", calcul="moteur",
    fonction="src/labuse/api/anti_fiche.py (motifs RÉDHIBITOIRE/VIGILANCE de la cascade)",
    reservoirs=("abf_merimee", "deal_ppr", "georisques_api", "znieff_inpn",), portee="run"),
 "n_extraits_plu": C("extraits (règlement)", "nombre", "commune",
    "extraits de règlement servis par commune (corpus)",
    moteur="commune_compteurs", calcul="moteur",
    fonction="src/labuse/registre/moteurs/commune.py:etat_corpus_plu",
    reservoirs=("gpu_plu_api_carto", "sudocuh",), portee="live"),
 "n_communes_rnu": C("au RNU", "nombre", "global",
    "communes au statut rnu du corpus (registre config/rnu_communes.yaml)",
    moteur="commune_compteurs", calcul="moteur",
    fonction="src/labuse/registre/moteurs/commune.py:etat_corpus_plu (n_rnu)",
    reservoirs=("sudocuh",), portee="live"),
 "simulplu_resultat": C("Simuler un changement (parcelles gagnées)", "nombre", "commune",
    "re-verdict cascade sous zonage hypothétique (dryrun)",
    moteur="cascade", calcul="moteur", fonction="src/labuse/api/moteurs.py:56-124",
    reservoirs=("gpu_plu_api_carto",), portee="run"),
 "comparateur_composite": C("Score composite", "nombre", "commune",
    "moyenne pondérée min-max des 6 axes présents, poids réglables",
    moteur="commune_compteurs", calcul="moteur",
    fonction="src/labuse/registre/moteurs/commune.py:composite_communes",
    reservoirs=("cosia", "dvf", "sitadel",), portee="run"),
 "stock_opportunites": C("Stock d'opportunités (brûlantes + chaudes)", "nombre", "commune",
    "count tiers brûlante+chaude au run servi, par insee",
    moteur="scoring_p_v2", calcul="moteur", fonction="src/labuse/api/comparateur.py:47-50",
    reservoirs=("cosia", "dvf", "sitadel",), portee="run"),
 "velocite_delai_median_mois": C("Vélocité admin (délai médian dépôt→autorisation, mois)", "nombre", "commune",
    "percentile_cont(0.5) sur m10_permit_delais famille logements",
    moteur="commune_compteurs", calcul="moteur",
    fonction="src/labuse/registre/moteurs/commune.py:indicateurs_communes (CTE velo)",
    reservoirs=("sitadel",), portee="live"),
 "permis_5a_n": C("Permis de la commune sur 5 ans (SITADEL)", "nombre", "commune",
    "count sitadel_permits de la commune, fenêtre 5 ans, sans rayon (commune entière)",
    moteur="commune_compteurs", calcul="moteur",
    fonction="src/labuse/registre/moteurs/commune.py:indicateurs_communes (CTE permis)",
    reservoirs=("sitadel",), portee="live"),
 "deficit_sru_pts": C("Déficit SRU (objectif − taux LLS, points)", "nombre", "commune",
    "greatest(objectif_pct − taux_lls, 0) depuis commune_contexte_sru",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/comparateur.py:56",
    reservoirs=("sru_dhup",), portee="live",
    table="commune_contexte_sru (objectif_pct, taux_lls)"),
 "pression_zan_ha": C("Pression ZAN (ENAF consommé 2021-2024, ha)", "nombre", "commune",
    "conso_2021_2024_m2 / 10000",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/comparateur.py:57",
    reservoirs=(), portee="live", table="commune_conso_enaf.conso_2021_2024_m2"),
 "prix_neuf_vefa_acte_eur_m2": C("Prix du neuf — VEFA à l'acte (€/m²)", "€/m²", "commune",
    "médiane VEFA déclarée à l'acte (neuf_vefa_commune, live, 36 mois) — USAGE RÉSERVÉ : le "
    "scoring (score_e) lit CET id ; affiché comparateur/communes/fiche commune sous libellé VEFA "
    "(scission 0-bis : ≠ prix_neuf_observe_eur_m2, jamais l'un sous le libellé de l'autre)",
    moteur="marche_service", calcul="moteur",
    fonction="src/labuse/ingestion/dvf_marche.py:neuf_vefa_commune (via marche_service, profil neuf_vefa)",
    reservoirs=("dvf",), portee="live"),
 "prix_neuf_observe_eur_m2": C("Prix du neuf — observé (€/m²)", "€/m²", "commune",
    "neuf observé ≤ 3 ans après achèvement (resolve_prix_neuf_marche : bassin sourcé > secteur > "
    "commune > repli île) — USAGE RÉSERVÉ : bilan et exports (fiche, PDF) lisent CET id "
    "(arbitrage Q3 ; scission 0-bis)",
    moteur="marche_service", calcul="moteur",
    fonction="src/labuse/ingestion/dvf_prix_neuf.py:resolve_prix_neuf_marche "
             "(servi par faisabilite/bilan.py:resolve_prix_sortie_servi)",
    reservoirs=("dvf",), portee="live"),
 "prix_ancien_median_eur_m2": C("€/m² ancien", "€/m²", "commune",
    "médiane DVF ventes strictes, filtre de retenue du baromètre",
    moteur="marche_service", calcul="moteur", fonction="src/labuse/api/moteurs.py:prix_ancien_communes (partagé PDF baromètre)",
    reservoirs=("dvf",), portee="live"),
 "n_parcelles_pm": C("Parcelles détenues", "nombre", "proprietaire",
    "count parcelle_personne_morale par SIREN (millésime 2025)",
    moteur="proprietaire_historique", calcul="moteur",
    fonction="src/labuse/registre/moteurs/proprietaire.py:compte_parcelles_pm "
             "(délégation — le calcul vit dans api/modules.py:patrimoine, une seule vérité)",
    reservoirs=("dgfip_parcelles_pm",), portee="live"),
 "prod_spec_kwh_kwc": C("Productible", "nombre", "parcelle",
    "productible PVGIS SARAH3 gelé au run du builder (parcel_solar)",
    moteur="solaire", calcul="moteur", fonction="src/labuse/api/modules.py:prospection_solaire",
    reservoirs=("bd_topo", "pvgis",), portee="run"),
 "azimut_bati_deg": C("Azimut (Estimé)", "nombre", "parcelle",
    "azimut du bâti principal, Estimé",
    moteur="solaire", calcul="moteur", fonction="src/labuse/ingestion/solaire.py (ST_OrientedEnvelope)",
    reservoirs=("bd_topo",), portee="run"),
 "n_piscines": C("Piscines détectées", "nombre", "commune",
    "count parcel_equipements piscine (BD ORTHO 2025, ~90,7 %)",
    moteur="commune_compteurs", calcul="moteur",
    fonction="src/labuse/registre/moteurs/commune.py:compte_piscines",
    reservoirs=("bd_ortho",), portee="live"),
 "mutations_12m_n": C("Mutations 12 mois", "nombre", "commune",
    "count dvf_mutations sur les 12 derniers mois DE DONNÉES (pas calendaire)",
    moteur="commune_compteurs", calcul="moteur",
    fonction="src/labuse/registre/moteurs/commune.py:mutations_12m",
    reservoirs=("dvf",), portee="live"),
 "acquisitions_pm_n": C("Acquisitions récentes (PM)", "nombre", "commune",
    "diff CONSTAT entre millésimes PM, maille commune",
    moteur="proprietaire_historique", calcul="moteur", fonction="src/labuse/api/app.py:commune_acquisitions_pm",
    reservoirs=("dgfip_parcelles_pm",), portee="live"),
 "permis_12m_n": C("Permis de la commune sur 12 mois", "nombre", "commune",
    "count sitadel_permits de la commune, fenêtre 12 mois, sans rayon (commune entière)",
    moteur="commune_compteurs", calcul="moteur",
    fonction="src/labuse/registre/moteurs/commune.py:compte_permis_commune",
    reservoirs=("sitadel",), portee="live"),
 "point_mort_n": C("Permis au point mort", "nombre", "commune",
    "permis autorisés sans DOC/DAACT dans la fenêtre",
    moteur="commune_compteurs", calcul="moteur",
    fonction="src/labuse/registre/moteurs/commune.py:permis_point_mort",
    reservoirs=("sitadel",), portee="live"),
 "n_densifiables": C("Parcelles densifiables", "nombre", "commune",
    "count parcel_renouvellement au run servi",
    moteur="renouvellement", calcul="moteur", fonction="src/labuse/api/app.py:renouvellement_liste",
    reservoirs=(), portee="run"),
 "population_zone": C("Habitants (zone)", "nombre", "zone",
    "somme carreaux Filosofi 200 m intersectant l'isochrone",
    moteur="zone", calcul="moteur", fonction="src/labuse/zone.py (population_zone — point Filosofi UNIQUE)",
    reservoirs=("filosofi_carreaux",), portee="live"),
 "n_concurrents_zone": C("Concurrents (NAF)", "nombre", "zone",
    "count sirene_etablissements du NAF choisi dans la zone, chacun avec son temps",
    moteur="zone", calcul="moteur", fonction="src/labuse/zone.py (comptages_zone)",
    reservoirs=("sirene_etablissements",), portee="live"),
 "emplois_fourchette": C("Emplois (fourchette)", "tranche", "zone",
    "somme des tranches d'effectifs SIRENE (jamais un point)",
    moteur="zone", calcul="moteur", fonction="src/labuse/zone.py",
    reservoirs=("sirene_etablissements",), portee="live",
    domaine_source="tranches d'effectifs SIRENE (nomenclature INSEE)"),
 "revenu_approche_eur": C("Revenu (valeur approchée)", "€", "zone",
    "niveau de vie approché N/M carreaux couverts (i_est_200)",
    moteur="zone", calcul="moteur", fonction="src/labuse/zone.py",
    reservoirs=("filosofi_carreaux",), portee="live"),
 "trafic_mja": C("Trafic (MJA)", "nombre", "zone",
    "comptage MJA du tronçon RN le plus proche, millésime porté par tronçon",
    moteur=None, calcul="passe_plat", fonction="src/labuse/zone.py",
    reservoirs=("trafic_rn",), portee="live", table="trafic_rn.tmja"),
 "annonces_actives_n": C("Biens en vente", "nombre", "commune",
    "count pige_biens actifs a_qualifier=false ; n<5 → NULL insuffisant",
    moteur="marche_pige", calcul="moteur", fonction="src/labuse/pige/marche.py:71-91",
    reservoirs=("radar_pige",), portee="live"),
 "prix_demande_median_eur_m2": C("Prix demandé (médiane)", "€/m²", "commune",
    "médiane des prix affichés terrain/bâti, n<5 masqué",
    moteur="marche_pige", calcul="moteur", fonction="src/labuse/pige/marche.py:71-91",
    reservoirs=("radar_pige",), portee="live"),
 "delai_vente_median_j": C("Délai médian", "nombre", "commune",
    "médiane 1re vue → retrait/vente",
    moteur="marche_pige", calcul="moteur", fonction="src/labuse/pige/marche.py",
    reservoirs=("radar_pige",), portee="live"),
 "ecart_demande_acte_pct": C("Écart demandé/acté", "%", "commune",
    "médiane demandé vs médiane DVF actée, servi dès SEUIL_N biens",
    moteur="marche_pige", calcul="moteur", fonction="src/labuse/api/fiche_commune.py:16-58 (comparable, partagé)",
    reservoirs=("dvf", "radar_pige",), portee="live"),
 "rang_tier": C("Rang (dans le tier)", "nombre", "parcelle",
    "rang au sein du tier",
    moteur="scoring_p_v2", calcul="moteur", fonction="src/labuse/api/app.py:3283",
    reservoirs=(), portee="run"),
 "prix_terrain_secteur_eur_m2": C("Terrain nu secteur", "€/m²", "parcelle",
    "médiane DVF rayon adaptatif 500→1500 m, trim 5 %, min 8 ventes, indice fiabilité",
    moteur="sector_price", calcul="moteur", fonction="src/labuse/faisabilite/bilan.py (sector_price)",
    reservoirs=("cadastre_api_carto", "dvf",), portee="live"),
 "prix_sortie_bati_eur_m2": C("Prix de sortie — bâti secteur", "€/m²", "parcelle",
    "sector_price PARCELLE (n, rayon effectif, période) servi AU SERVEUR par _q_v2_fiche — "
    "même phrase écran et PDF (EXPORTS-1 1.3, plus de calcul front)",
    moteur="sector_price", calcul="moteur",
    fonction="src/labuse/api/app.py:_q_v2_fiche (sector_price via marche_service, phrase_prix_ancien)",
    reservoirs=("dvf",), portee="live"),
 "ventes_100m_n": C("Ventes à moins de 100 m (36 mois)", "nombre", "parcelle",
    "count mutations DVF à <100 m sur 36 mois (profil voisinage_100m, config/dvf_profils.yaml) + médiane",
    moteur="marche_service", calcul="moteur",
    fonction="src/labuse/api/site_voisinage.py:voisinage_proche (profil voisinage_100m)",
    reservoirs=("dvf",), portee="live"),
 "pente_deg": C("Pente", "nombre", "parcelle",
    "pente moyenne parcelle (RGE ALTI), flag terrassement",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/app.py:3283 (viabilisation)",
    reservoirs=("rge_alti",), portee="live", table="parcel_terrain.pente_moy_deg"),
 "piscine_m2": C("Piscine ~m²", "m²", "parcelle",
    "surface détectée parcel_equipements (BD ORTHO 2025)",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/app.py:3283",
    reservoirs=("bd_ortho",), portee="live", table="parcel_equipements.piscine_surface_m2"),
 "distance_arret_m": C("Transport public — au plus proche", "m", "parcelle",
    "plus proche arrêt/pôle (distance en m)",
    moteur="parcelle_proximites", calcul="moteur",
    fonction="src/labuse/registre/moteurs/parcelle.py:plus_proche",
    reservoirs=("gtfs_pan", "osm_transport",), portee="live"),
 "n_permis_proximite": C("Permis à 500 m sur 24 mois", "nombre", "parcelle",
    "permis Sitadel dans le rayon 500 m, fenêtre 24 mois — LE profil client (arbitrage Q7), "
    "paramètres TRANSMIS au moteur (EXPORTS-1 4.1, plus jamais les défauts 300 m · 5 ans)",
    moteur="marche_service", calcul="moteur",
    fonction="src/labuse/marche_service.py:permits (profil flash_500m → nearby_permits)",
    reservoirs=("sitadel",), portee="live"),
 "depots_secteur_n": C("Déposés sur le secteur (36 mois)", "nombre", "zone",
    "dépôts Sitadel de la section cadastrale (préfixe IDU 10), fenêtre 36 mois "
    "(DEPOTS_FENETRE_MOIS, profil fiche_36m)",
    moteur="marche_service", calcul="moteur",
    fonction="src/labuse/ingestion/permits.py:depots_recents (via marche_service, profil fiche_36m)",
    reservoirs=("sitadel",), portee="live"),
 "type_proprietaire": C("Propriétaire (type)", "classe", "proprietaire",
    "personne morale (dénomination) / personne physique non recensée — fichier PM "
    "parcelle_personne_morale, millésime 2025 (même assiette que la carte — EXPORTS-1 5.4 : "
    "la ligne « non renseigné » stockée au run est rebranchée sur le fichier PM à la lecture)",
    moteur=None, calcul="passe_plat",
    fonction="src/labuse/api/app.py:3586 (proprietaire_moral, parcelle_personne_morale) ; "
             "garde de lecture cascade/context.py (EXPORTS-1 5.4)",
    reservoirs=("dgfip_parcelles_pm",), portee="live",
    table="parcelle_personne_morale.denomination (millésime 2025)",
    domaine=("personne morale", "personne physique non recensée"),
    domaine_source="fichier PM DGFiP (les PP ne sont pas diffusées)"),
 "verdict_icd": C("Confiance données", "verdict", "parcelle",
    "verdict de complétude des couches + liste des manquants",
    moteur="cascade", calcul="moteur", fonction="src/labuse/api/app.py:3283 (bloc icd)",
    reservoirs=(), portee="run"),
 "divisible_classe": C("Division (candidate)", "classe", "parcelle",
    "présence dans division_or_candidates — run figé q_v10, workflow de revue",
    moteur="division_or", calcul="moteur", fonction="src/labuse/api/app.py:2692-2696",
    reservoirs=("cadastre_api_carto", "cosia", "gpu_plu_api_carto",), portee="run",
    domaine=("candidate", "non_candidate", "non_recalculee"),
    domaine_source="présence dans division_or_candidates au run servi (2.3 : run mort jamais servi)"),
 "statut_plu": C("Règles d'urbanisme (statut)", "classe", "commune",
    "RNU (registre) l'emporte ; sinon statut du registre veille_plu",
    moteur="plu_destinations", calcul="moteur", fonction="src/labuse/api/fiche_commune.py:137-144",
    reservoirs=("gpu_plu_api_carto", "sudocuh",), portee="live",
    domaine=("RNU", "à jour", "en révision", "en élaboration", "en modification", "document local"),
    domaine_source="_PLU_STATUT (api/fiche_commune.py) + registre RNU (config/rnu_communes.yaml)"),
 "zan_reste_ha": C("Enveloppe ZAN (reste)", "nombre", "commune",
    "enveloppe restante estimée depuis conso ENAF",
    moteur="commune_compteurs", calcul="moteur",
    fonction="src/labuse/api/rarete.py:compute_rarete (reste_zan_ha — producteur nommé, délégation)",
    reservoirs=(), portee="live"),
 "taux_lls_pct": C("Taux LLS", "%", "commune",
    "taux LLS de l'inventaire SRU",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/fiche_commune.py (commune_contexte_sru)",
    reservoirs=("sru_dhup",), portee="live", table="commune_contexte_sru.taux_lls"),
 "plh_objectif_logements_an": C("Objectif logements/an", "logements", "commune",
    "objectif PLH, chaque chiffre porte sa référence doc+page",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/fiche_commune.py (plh_epci)",
    reservoirs=("plh_epci",), portee="live", table="plh_epci (objectif logements/an, par EPCI)"),
 "prix_terrain_zone_eur_m2": C("Terrain nu (zone U / AU)", "€/m²", "commune",
    "médiane DVF terrain nu par famille de zone, seuil 10 ventes",
    moteur="marche_service", calcul="moteur", fonction="src/labuse/faisabilite/marche_commune.py:ligne2_terrain_zone",
    reservoirs=("dvf", "gpu_plu_api_carto",), portee="live"),
 "loyer_median_eur_m2": C("Loyer médian", "€/m²", "commune",
    "estimation locative loyers.py — entrées à confirmer (DOUTE)",
    moteur="loyers", calcul="moteur", fonction="src/labuse/api/fiche_commune.py (loyer)",
    reservoirs=(), portee="live"),
 "n_parcelles_commune": C("N parcelles", "nombre", "commune",
    "count parcels par commune",
    moteur="commune_compteurs", calcul="moteur",
    fonction="src/labuse/registre/moteurs/commune.py:compte_parcelles_commune",
    reservoirs=("cadastre_api_carto",), portee="live"),
 "part_zone_U_pct": C("Zonage — U", "%", "commune",
    "surface cadastrée U / surface zonée totale (somme=100 %)",
    moteur="zonage_commune", calcul="moteur",
    fonction="src/labuse/registre/moteurs/zonage.py:parts_zonage_surface",
    reservoirs=("cadastre_api_carto", "gpu_plu_api_carto",), portee="live"),
 "part_zone_AU_pct": C("Zonage — AU", "%", "commune",
    "surface AU / surface zonée",
    moteur="zonage_commune", calcul="moteur",
    fonction="src/labuse/registre/moteurs/zonage.py:parts_zonage_surface",
    reservoirs=("cadastre_api_carto", "gpu_plu_api_carto",), portee="live"),
 "part_zone_A_pct": C("Zonage — A", "%", "commune",
    "surface A / surface zonée (Saint-Paul : 35,8 % — la part en PARCELLES vaut 17,8 %)",
    moteur="zonage_commune", calcul="moteur",
    fonction="src/labuse/registre/moteurs/zonage.py:parts_zonage_surface",
    reservoirs=("cadastre_api_carto", "gpu_plu_api_carto",), portee="live"),
 "part_zone_N_pct": C("Zonage — N", "%", "commune",
    "surface N / surface zonée (Saint-Paul : 47,2 % — la part en PARCELLES vaut 6,8 %)",
    moteur="zonage_commune", calcul="moteur",
    fonction="src/labuse/registre/moteurs/zonage.py:parts_zonage_surface",
    reservoirs=("cadastre_api_carto", "gpu_plu_api_carto",), portee="live"),
 "ppr_pct": C("PPR (part des parcelles)", "%", "commune",
    "part des parcelles de la commune intersectant la couche ppr",
    moteur="commune_compteurs", calcul="moteur",
    fonction="src/labuse/registre/moteurs/commune.py:pct_parcelles_couche",
    reservoirs=("deal_ppr",), portee="live"),
 "catnat_n": C("Arrêtés CatNat", "nombre", "commune",
    "count catnat_arretes",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/fiche_commune.py",
    reservoirs=(), portee="live", table="catnat_arretes (count par insee)"),
 "habitants_n": C("Habitants", "nombre", "commune",
    "population INSEE/Filosofi commune",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/fiche_commune.py:123 (population)",
    reservoirs=("filosofi_carreaux", "insee_rp_logement",), portee="live",
    table="filosofi_carreaux_200m (Σ ind des carreaux de la commune)"),
 "vacance_pct": C("Vacance", "%", "commune",
    "100 × vacants / logements (RP)",
    moteur="commune_compteurs", calcul="moteur",
    fonction="src/labuse/registre/moteurs/commune.py:vacance_pct",
    reservoirs=("insee_rp_logement",), portee="live"),
 "qpv_n": C("QPV", "nombre", "commune",
    "count QPV intersectant la commune",
    moteur="commune_compteurs", calcul="moteur",
    fonction="src/labuse/registre/moteurs/commune.py:qpv_commune",
    reservoirs=("qpv_2024",), portee="live"),
 "prix_demande_eur": C("Prix demandé", "€", "annonce",
    "fait déclaré de l'annonce (pige_faits), jamais le texte",
    moteur=None, calcul="passe_plat", fonction="src/labuse/pige/client.py",
    reservoirs=("radar_pige",), portee="live", table="pige_faits.prix"),
 "copilote_compte_parcelles": C("Compte de parcelles (réponse)", "nombre", "global",
    "MÊME facette canonique que le filtre écran (égalité verrouillée)",
    moteur="copilote_outils", calcul="moteur",
    fonction="src/labuse/copilote_v2/outils.py:compter_parcelles",
    reservoirs=("cadastre_api_carto",), portee="run"),
 "destination_statut": C("Peut-on ouvrir une activité ? (verdict)", "verdict", "parcelle",
    "MÊME moteur plu.destinations que fiche et étude de zone",
    moteur="plu_destinations", calcul="moteur", fonction="src/labuse/copilote_v2/outils.py:573-599",
    reservoirs=("gpu_plu_api_carto", "sudocuh",), portee="live"),
 "n_veilles": C("Veilles actives", "nombre", "global",
    "count veilles du compte",
    moteur="plateforme_compteurs", calcul="moteur",
    fonction="src/labuse/copilote_v2/veilles.py:lister (producteur nommé, délégation)",
    reservoirs=(), portee="live"),
 "projet_cadrage_n": C("Parcelles (cadrage)", "nombre", "global",
    "count parcelles du projet",
    moteur="plateforme_compteurs", calcul="moteur",
    fonction="src/labuse/api/projets.py:_counts_by_projet (producteur nommé, délégation)",
    reservoirs=(), portee="run"),
 "projet_retenues_n": C("Retenues", "nombre", "global",
    "count retenues",
    moteur="plateforme_compteurs", calcul="moteur",
    fonction="src/labuse/api/projets.py:_counts_by_projet (producteur nommé, délégation)",
    reservoirs=(), portee="run"),
 "crm_cartes_n": C("Cartes par colonne", "nombre", "global",
    "count par colonne",
    moteur="plateforme_compteurs", calcul="moteur",
    fonction="src/labuse/registre/moteurs/plateforme.py:cartes_par_colonne",
    reservoirs=(), portee="live"),
 "n_notifications": C("Notifications non lues", "nombre", "global",
    "count event_log non lus du compte",
    moteur="plateforme_compteurs", calcul="moteur",
    fonction="src/labuse/registre/moteurs/plateforme.py:notifications_non_lues",
    reservoirs=(), portee="live"),
 "n_bascules_7j": C("Bascules (7 jours)", "nombre", "global",
    "bascules de tier détectées vs run précédent",
    moteur="plateforme_compteurs", calcul="moteur",
    fonction="src/labuse/registre/moteurs/plateforme.py:bascules_tiers_hauts",
    reservoirs=(), portee="run"),
 "n_biens_du_jour": C("Biens du jour (digest)", "nombre", "global",
    "biens validés du jour, cartes HTML plafond 10 + « et N autres »",
    moteur="marche_pige", calcul="moteur", fonction="src/labuse/api/events.py:1160-1216",
    reservoirs=("radar_pige",), portee="live"),
 "n_biens_veille": C("NB_BIENS (Brevo 13)", "nombre", "global",
    "len(matches) de LA veille — un mail par veille",
    moteur="marche_pige", calcul="moteur", fonction="src/labuse/pige/digests.py:303-313",
    reservoirs=("radar_pige",), portee="live"),
 "n_parcelles_ile": C("Parcelles (accueil)", "nombre", "global",
    "count parcels mesuré, jamais en dur",
    moteur="plateforme_compteurs", calcul="moteur",
    fonction="src/labuse/registre/moteurs/plateforme.py:compte_parcelles_ile",
    reservoirs=("cadastre_api_carto",), portee="live"),
 "n_sources": C("Sources (accueil)", "nombre", "global",
    "count des sources AFFICHÉES (66 au 05/09) — définition canonique WHERE_AFFICHEES "
    "(sources_catalog), servie accueil ET écran Circuit",
    moteur="flux", calcul="moteur",
    fonction="src/labuse/flux.py:construire_flux (producteur nommé, délégation — "
             "l'accueil lit la même définition WHERE_AFFICHEES)",
    reservoirs=(), portee="live"),
 "run_label_servi": C("Run servi (pied)", "classe", "global",
    "label du run servi",
    moteur=None, calcul="constante", fonction="src/labuse/api/accueil.py:57",
    reservoirs=(), portee="run", type="texte"),
 "prix_flash_eur": C("Rapport Flash — 79 €", "€", "global",
    "prix de l'offre Flash, source unique offres.py",
    moteur=None, calcul="constante", fonction="src/labuse/offres.py (source unique des prix)",
    reservoirs=(), portee="live"),
 "n_a_faire": C("À faire (pilotage)", "nombre", "global",
    "gestes attendus : nouvelle_version + a_rafraichir (arbitre unique etats_sources)",
    moteur="plateforme_compteurs", calcul="moteur",
    fonction="src/labuse/etats_sources.py:compteurs (sur lister_etats — arbitre unique, délégation)",
    reservoirs=(), portee="live"),
 "n_sources_surveillees": C("sous veille (écran Circuit)", "nombre", "global",
    "49 = lignes source_veille actives à vraie sonde, compte brut",
    moteur="flux", calcul="moteur",
    fonction="src/labuse/flux.py:construire_flux (comptes.surveillees — producteur nommé, délégation)",
    reservoirs=(), portee="live"),
 "ecart_candidat_pct": C("Écart candidat vs servi", "%", "global",
    "comparaison distribution tiers candidat/servi",
    moteur="golden_ops", calcul="moteur",
    fonction="src/labuse/golden_ops.py:comparer (producteur nommé, délégation)",
    reservoirs=(), portee="run"),
 "ia_cout_eur": C("Conso IA (€)", "€", "global",
    "somme cout par modèle/surface 30 j (ledger ia_log)",
    moteur="plateforme_compteurs", calcul="moteur",
    fonction="src/labuse/registre/moteurs/plateforme.py:conso_ia_mois (+ conso_ia_30j)",
    reservoirs=(), portee="live"),
 "n_depots_a_verifier": C("Dépôts à vérifier", "nombre", "global",
    "count pige_faits en attente de validation (file d'extraction Radar)",
    moteur="plateforme_compteurs", calcul="moteur",
    fonction="src/labuse/registre/moteurs/plateforme.py:depots_a_verifier",
    reservoirs=("radar_pige",), portee="live"),
 "n_comptes_actifs": C("Comptes actifs", "nombre", "global",
    "count comptes par statut",
    moteur="plateforme_compteurs", calcul="moteur",
    fonction="src/labuse/registre/moteurs/plateforme.py:comptes_actifs",
    reservoirs=(), portee="live"), # ── longue traîne (lot 1.3) — robinets à zéro de l'inventaire, chiffres déclarés ici ──
 "n_procedures_plu": C("Procédures d'urbanisme (en cours)", "nombre", "commune",
    "compte des procédures PLU non réconciliées (révision/élaboration) du registre veille_plu",
    moteur="commune_compteurs", calcul="moteur",
    fonction="src/labuse/veille_plu.py:communes_en_procedure (producteur nommé, délégation)",
    reservoirs=("sudocuh",), portee="live"),
 "assemblage_parcelles_n": C("Parcelles assemblées", "nombre", "parcelle",
    "compte des parcelles retenues dans l'assemblage courant",
    moteur="parcelle_proximites", calcul="moteur",
    fonction="src/labuse/registre/moteurs/parcelle.py:assemblage_assiette "
             "(délégation — le calcul vit dans api/moteurs.py:assemblage, une seule vérité)",
    reservoirs=("cadastre_api_carto",), portee="live"),
 "assemblage_surface_m2": C("Surface assemblée", "m²", "parcelle",
    "somme des surfaces cadastrales des parcelles de l'assemblage",
    moteur="parcelle_proximites", calcul="moteur",
    fonction="src/labuse/registre/moteurs/parcelle.py:assemblage_assiette "
             "(délégation — le calcul vit dans api/moteurs.py:assemblage, une seule vérité)",
    reservoirs=("cadastre_api_carto",), portee="live"),
 "courrier_demandes_n": C("Courriers demandés", "nombre", "global",
    "compte des demandes de courrier propriétaire du compte",
    moteur="plateforme_compteurs", calcul="moteur",
    fonction="src/labuse/courrier.py:demandes_de (producteur nommé, délégation)",
    reservoirs=(), portee="live"),
 "annee_ortho": C("Année de la photographie aérienne", "date", "global",
    "millésime du fond ortho affiché (registre ORTHO_YEARS)",
    moteur=None, calcul="constante", fonction="frontend/src/components/map/basemaps.ts (ORTHO_YEARS)",
    reservoirs=("bd_ortho",), portee="live"),
 "pipeline_entrees_n": C("Entrées du pipeline", "nombre", "global",
    "compte des entrées du pipeline (retour terrain) par statut, périmètre du compte",
    moteur="plateforme_compteurs", calcul="moteur",
    fonction="src/labuse/registre/moteurs/plateforme.py:cartes_par_colonne",
    reservoirs=(), portee="live"),
 "couverture_commune_pct": C("Couverture des sources par commune", "%", "commune",
    "part des communes couvertes par chaque source (taux d'ingestion)",
    moteur="commune_compteurs", calcul="moteur",
    fonction="src/labuse/registre/moteurs/commune.py:couverture_sources",
    reservoirs=(), portee="live"),
 "autres_loges_pct": C("logés gratuitement", "%", "commune",
    "100 − locataires_pct − proprietaires_pct (INSEE RP), arrondi 0,1, plancher 0 — calculé au SERVEUR (lot 2.4, avant : ContextePanel.tsx:526)",
    moteur="commune_compteurs", calcul="moteur",
    fonction="src/labuse/registre/moteurs/commune.py:autres_loges_pct",
    reservoirs=("insee_rp_logement",), portee="live"),
 "parcelles_par_zone_n": C("parcelles en zone …", "nombre", "commune",
    "compte de parcelles par famille/zone du filtre (JAMAIS servi comme une part — décision Vic 2.1 : les parts de zonage sont les parts de surface)",
    moteur="zonage_commune", calcul="moteur",
    fonction="src/labuse/registre/moteurs/zonage.py:parcelles_par_zone",
    reservoirs=("gpu_plu_api_carto", "cadastre_api_carto"), portee="live"),
 "usage_outil_n": C("Usage des outils (30 j)", "nombre", "global",
    "compte d'événements d'usage par outil sur la fenêtre choisie (7/30/90 j)",
    moteur="plateforme_compteurs", calcul="moteur",
    fonction="src/labuse/registre/moteurs/plateforme.py:usage_par_outil",
    reservoirs=(), portee="live"), # ── 0-bis réconciliation EXPORTS-1/ZONE-1 (05/09) ──
 "mixite_clause": C("Mixité sociale (clause)", "verdict", "parcelle",
    "déclenchement de la clause de mixité Art. 2 : SDP ≥ seuil OU logements ≥ seuil OU terrain "
    "> seuil (seuils des hypothèses de bilan, source déclarée sinon « Estimé ») — bloc unique "
    "servitude + déclenchement (EXPORTS-1 5.1)",
    moteur="bilan_promoteur", calcul="moteur",
    fonction="src/labuse/faisabilite/bilan.py:_clause_mixite",
    reservoirs=("gpu_plu_api_carto",), portee="live"),
 "cout_construction_saisi_eur_m2": C("Coût de construction (saisi)", "€/m²", "parcelle",
    "hypothèse SAISIE par le client dans la calculette du bilan — jamais un chiffre LABUSE",
    moteur=None, calcul="passe_plat",
    fonction="src/labuse/api/app.py:parcel_export_pdf (calculette — saisie client)",
    reservoirs=(), portee="projet",
    table="(saisie client — corps de requête de la calculette, aucune table)"),
 "marge_frais_saisie_pct": C("Marge et frais (saisis)", "%", "parcelle",
    "hypothèse SAISIE par le client dans la calculette du bilan — jamais un chiffre LABUSE",
    moteur=None, calcul="passe_plat",
    fonction="src/labuse/api/app.py:parcel_export_pdf (calculette — saisie client)",
    reservoirs=(), portee="projet",
    table="(saisie client — corps de requête de la calculette, aucune table)"),
 "prix_demande_saisi_eur": C("Prix demandé (saisi)", "€", "parcelle",
    "prix demandé SAISI par le client (écart au prix demandé calculé dessus) — jamais un "
    "chiffre LABUSE ; ≠ prix_demande_eur (fait déclaré d'une annonce Radar)",
    moteur=None, calcul="passe_plat",
    fonction="src/labuse/api/app.py:parcel_export_pdf (calculette — saisie client)",
    reservoirs=(), portee="projet",
    table="(saisie client — corps de requête de la calculette, aucune table)"),
 # ══ CIRCUIT-2 lot 1.2/1.3 — LES COUCHES (type `couche` : table/tuilage + fabrication) ══
 "verdict_couche": C("Verdict · Classement servi (couche)", "couche", "parcelle",
    "aplat des tiers du run servi sur toutes les parcelles (tuiles vectorielles)",
    moteur="flags", calcul="moteur", fonction="src/labuse/api/tiles.py (MVT parcel_flags)",
    reservoirs=("bd_topo", "cosia", "dvf", "filosofi_carreaux", "sitadel",), portee="run",
    type="couche", table="parcel_flags → tuiles MVT (mvt_meta porte le run et la date)",
    fabrication="build-mvt"),
 "zonage_plu_couche": C("Zonage PLU par parcelle (couche)", "couche", "parcelle",
    "chaque parcelle peinte de la famille de sa zone (calée cadastre), code exact au zoom/clic",
    moteur="zone_servie", calcul="moteur", fonction="src/labuse/api/app.py:map_layers_geojson (plu_gpu_zone)",
    reservoirs=("gpu_plu_api_carto",), portee="live",
    type="couche", table="parcel_zone_plu", fabrication="requete",
    domaine=("U", "AU", "A", "N"), domaine_source="familles de zones du GPU"),
 "gpu_brut_couche": C("Limites officielles PLU — GPU brut (couche)", "couche", "commune",
    "les aplats bruts du document opposable (contours d'origine, hors cadastre)",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/app.py:map_layers_geojson (plu_gpu)",
    reservoirs=("gpu_plu_api_carto",), portee="live",
    type="couche", table="spatial_layers (kind=zonage_plu_gpu)", fabrication="requete"),
 "cinquante_pas_couche": C("50 pas géométriques (couche)", "couche", "commune",
    "la bande littorale des 50 pas (81,20 m), régime foncier outre-mer",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/app.py:map_layers_geojson (cinquante_pas)",
    reservoirs=("cinquante_pas_deal",), portee="live",
    type="couche", table="spatial_layers (kind=cinquante_pas)", fabrication="requete"),
 "znieff_couche": C("ZNIEFF type I & II (couche)", "couche", "commune",
    "inventaire du patrimoine naturel (type I secteur sensible, type II grand ensemble)",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/app.py:map_layers_geojson (znieff)",
    reservoirs=("znieff_inpn",), portee="live",
    type="couche", table="spatial_layers (kind=znieff, subtype=type I/II)", fabrication="requete",
    domaine=("type I", "type II"), domaine_source="INPN/MNHN (PatriNat)"),
 "bpe_couche": C("Équipements INSEE BPE (couche)", "couche", "commune",
    "équipements géolocalisés BPE (source statistique, distincte d'OSM — jamais fusionnées)",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/app.py:map_layers_geojson (amenite_bpe)",
    reservoirs=("bpe_insee",), portee="live",
    type="couche", table="spatial_layers (kind=amenite_bpe)", fabrication="requete"),
 "alea_inondation_couche": C("Aléa inondation (couche)", "couche", "commune",
    "secteurs exposés à l'aléa inondation avec leur NIVEAU (cartographie d'aléas DEAL — "
    "l'exposition au phénomène, pas la règle PPR)",
    moteur=None, calcul="passe_plat",
    fonction="src/labuse/api/app.py:map_layers_geojson (georisque_alea, subtype=inondation)",
    reservoirs=("deal_ppr",), portee="live",
    type="couche", table="spatial_layers (kind=georisque_alea)", fabrication="requete",
    domaine=("faible", "moyen", "fort"),
    domaine_source="niveau NORMALISÉ servi (attrs.niveau — layers_ingest._normalise_alea) ; le "
                   "degré DEAL brut (FAIBLE…TRES_ELEVE) voyage dans attrs.degre. RETOURS-13 : "
                   "ELEVE/TRES_ELEVE normalisés en « moyen » = bug — la sonde 4.2 contrôle la "
                   "distribution degre↔niveau"),
 "alea_mvt_couche": C("Aléa mouvement de terrain (couche)", "couche", "commune",
    "secteurs exposés à l'aléa mouvement de terrain avec leur NIVEAU (cartographie DEAL)",
    moteur=None, calcul="passe_plat",
    fonction="src/labuse/api/app.py:map_layers_geojson (georisque_alea, subtype=mouvement_terrain)",
    reservoirs=("deal_ppr",), portee="live",
    type="couche", table="spatial_layers (kind=georisque_alea)", fabrication="requete",
    domaine=("faible", "moyen", "fort"),
    domaine_source="niveau normalisé servi (attrs.niveau) ; degré DEAL brut en attrs.degre — "
                   "distribution contrôlée par la sonde 4.2"),
 "transport_couche": C("Transport public (couche)", "couche", "commune",
    "tracés et arrêts des 7 réseaux GTFS + téléphérique Papang (OSM)",
    moteur=None, calcul="passe_plat",
    fonction="src/labuse/api/app.py:map_layers_geojson (transport_ligne, transport_arret, telepherique)",
    reservoirs=("gtfs_pan", "osm_transport",), portee="live",
    type="couche", table="spatial_layers (kind=transport_ligne/transport_arret/telepherique)",
    fabrication="requete"),
 "axes_couche": C("Axes structurants (couche)", "couche", "commune",
    "axes routiers structurants (BD TOPO importance 1-2) + pôles d'échange",
    moteur=None, calcul="passe_plat",
    fonction="src/labuse/api/app.py:map_layers_geojson (axe_structurant, pole_echange)",
    reservoirs=("bd_topo", "osm_transport",), portee="live",
    type="couche", table="spatial_layers (kind=axe_structurant/pole_echange)", fabrication="requete"),
 "lignes_ht_couche": C("Lignes haute tension (couche)", "couche", "commune",
    "réseau de transport 63/90 kV (BD TOPO, aérien seul — la HTA n'a pas de source ouverte)",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/app.py:map_layers_geojson (ligne_ht)",
    reservoirs=("bd_topo",), portee="live",
    type="couche", table="spatial_layers (kind=ligne_ht)", fabrication="requete"),
 "tcsp_couche": C("Axe de transport structurant (couche)", "couche", "commune",
    "l'EXPRESS BAOBAB (Citalis/CINOR) — vue dérivée du GTFS (route BAO), jamais une ingestion neuve",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/app.py:map_layers_geojson (tcsp_axe)",
    reservoirs=("gtfs_pan",), portee="live",
    type="couche", table="spatial_layers (kind=transport_ligne WHERE route_id='BAO')",
    fabrication="vue"),
 "dispositifs_couche": C("Dispositifs et périmètres (couche)", "couche", "commune",
    "QPV, NPNRU/ANRU, TVA primo (buffer 500 m DÉRIVÉ des QPV), ZFANG et FRR (maille commune)",
    moteur=None, calcul="passe_plat",
    fonction="src/labuse/api/app.py:map_layers_geojson (qpv, tva_primo, anru, zfang, frr)",
    reservoirs=("qpv_2024", "npnru", "zfang", "frr_ex_zrr",), portee="live",
    type="couche", table="spatial_layers (kinds qpv/anru/zfang/frr ; tva_primo = buffer dérivé)",
    fabrication="requete"),
 "vefa_couche": C("Prix du logement neuf — VEFA (couche)", "couche", "commune",
    "aplat commune de la tranche VEFA (rampe), hachure sous 10 ventes — dérivé DVF live",
    moteur="marche_service", calcul="moteur",
    fonction="src/labuse/api/app.py:map_layers_geojson (vefa_neuf)",
    reservoirs=("dvf",), portee="live",
    type="couche", table="dvf_mutations_parcelle (agrégat live par commune)", fabrication="vue"),
 "densifier_couche": C("Densifier l'existant (couche)", "couche", "parcelle",
    "parcelles bâties à capacité résiduelle (segment renouvellement du run servi)",
    moteur="renouvellement", calcul="moteur",
    fonction="src/labuse/api/app.py:renouvellement_geojson",
    reservoirs=(), portee="run",
    type="couche", table="parcel_renouvellement (run servi)", fabrication="vue"),
 "ppr_couche": C("PPR multirisque (couche)", "couche", "commune",
    "zonage réglementaire des Plans de Prévention des Risques (la RÈGLE, ≠ l'aléa)",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/app.py:map_layers_geojson (ppr)",
    reservoirs=("deal_ppr",), portee="live",
    type="couche", table="spatial_layers (kind=ppr)", fabrication="requete"),
 "parc_national_couche": C("Parc national (couche)", "couche", "commune",
    "périmètre du Parc national de La Réunion (urbanisation très restreinte)",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/app.py:map_layers_geojson (parc_national)",
    reservoirs=("parc_national_inpn",), portee="live",
    type="couche", table="spatial_layers (kind=parc_national)", fabrication="requete"),
 "limites_parcelles_couche": C("Limites parcelles (couche)", "couche", "parcelle",
    "le contour gris de toutes les parcelles cadastrales (sans couleur)",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/tiles.py (contours MVT)",
    reservoirs=("cadastre_api_carto",), portee="live",
    type="couche", table="parcels.geom → tuiles", fabrication="build-mvt"),
 "communes_couche": C("Limites communes (couche)", "couche", "global",
    "frontières officielles des 24 communes (référentiel embarqué geo.api.gouv/IGN, seed)",
    moteur=None, calcul="passe_plat", fonction="frontend (contours embarqués au seed)",
    reservoirs=(), portee="live",
    type="couche", table="communes (contours, seed geo.api.gouv)", fabrication="requete"),
 "equip_osm_couche": C("Équipements OSM (couche)", "couche", "commune",
    "équipements du quotidien relevés dans OpenStreetMap (couverture partielle DITE — "
    "l'absence n'est pas une preuve)",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/app.py:map_layers_geojson (amenite)",
    reservoirs=("osm_overpass",), portee="live",
    type="couche", table="spatial_layers (kind=amenite)", fabrication="requete"),
 # ══ lot 1.3 — LES FONDS IGN (service + version de tuiles ; sonde de DISPONIBILITÉ seule) ══
 "tuiles_plan_ign": C("Plan IGN v2 (fond)", "couche", "global",
    "fond de plan vectoriel IGN, interrogé en direct (aucune ingestion)",
    moteur=None, calcul="passe_plat", fonction="frontend/src/components/map/basemaps.ts (WMTS)",
    reservoirs=(), portee="live", type="couche",
    table="WMTS data.geopf.fr — LAYER=GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2, VERSION=1.0.0, PM",
    fabrication="wmts_distant"),
 "tuiles_ortho_2025": C("Actuelle · Ortho Express 2025 (fond)", "couche", "global",
    "orthophoto 20 cm la plus récente réellement servie île-entière au 974 (vérifiée F4)",
    moteur=None, calcul="passe_plat", fonction="frontend/src/components/map/basemaps.ts (WMTS)",
    reservoirs=(), portee="live", type="couche",
    table="WMTS data.geopf.fr — LAYER=ORTHOIMAGERY.ORTHOPHOTOS.ORTHO-EXPRESS.2025, VERSION=1.0.0, PM",
    fabrication="wmts_distant"),
 "tuiles_ortho_1950_1965": C("Ortho 1950-1965 (fond)", "couche", "global",
    "mosaïque-période IGN (s'arrête ~z15, overzoom au-delà)",
    moteur=None, calcul="passe_plat", fonction="frontend/src/components/map/basemaps.ts (WMTS)",
    reservoirs=(), portee="live", type="couche",
    table="WMTS data.geopf.fr — LAYER=ORTHOIMAGERY.ORTHOPHOTOS.1950-1965, VERSION=1.0.0, PM",
    fabrication="wmts_distant"),
 "tuiles_ortho_2000_2005": C("Ortho 2000-2005 (fond)", "couche", "global",
    "mosaïque-période IGN vérifiée au 974",
    moteur=None, calcul="passe_plat", fonction="frontend/src/components/map/basemaps.ts (WMTS)",
    reservoirs=(), portee="live", type="couche",
    table="WMTS data.geopf.fr — LAYER=ORTHOIMAGERY.ORTHOPHOTOS2000-2005, VERSION=1.0.0, PM",
    fabrication="wmts_distant"),
 "tuiles_ortho_2006_2010": C("Ortho 2006-2010 (fond)", "couche", "global",
    "mosaïque-période IGN vérifiée au 974",
    moteur=None, calcul="passe_plat", fonction="frontend/src/components/map/basemaps.ts (WMTS)",
    reservoirs=(), portee="live", type="couche",
    table="WMTS data.geopf.fr — LAYER=ORTHOIMAGERY.ORTHOPHOTOS2006-2010, VERSION=1.0.0, PM",
    fabrication="wmts_distant"),
 "tuiles_ortho_2011_2015": C("Ortho 2011-2015 (fond)", "couche", "global",
    "mosaïque-période IGN vérifiée au 974",
    moteur=None, calcul="passe_plat", fonction="frontend/src/components/map/basemaps.ts (WMTS)",
    reservoirs=(), portee="live", type="couche",
    table="WMTS data.geopf.fr — LAYER=ORTHOIMAGERY.ORTHOPHOTOS2011-2015, VERSION=1.0.0, PM",
    fabrication="wmts_distant"),
 "tuiles_ortho_2016_2020": C("Ortho 2016-2020 (fond)", "couche", "global",
    "mosaïque-période IGN vérifiée au 974",
    moteur=None, calcul="passe_plat", fonction="frontend/src/components/map/basemaps.ts (WMTS)",
    reservoirs=(), portee="live", type="couche",
    table="WMTS data.geopf.fr — LAYER=ORTHOIMAGERY.ORTHOPHOTOS2016-2020, VERSION=1.0.0, PM",
    fabrication="wmts_distant"),
 "tuiles_ortho_2021_2023": C("Ortho 2021-2023 (fond)", "couche", "global",
    "mosaïque-période IGN vérifiée au 974",
    moteur=None, calcul="passe_plat", fonction="frontend/src/components/map/basemaps.ts (WMTS)",
    reservoirs=(), portee="live", type="couche",
    table="WMTS data.geopf.fr — LAYER=ORTHOIMAGERY.ORTHOPHOTOS2021-2023, VERSION=1.0.0, PM",
    fabrication="wmts_distant"),
 # ══ lot 1.2 — TEXTES d'origine externe (les deux hors_registre restants non-décor) ══
 "mairie_coordonnees": C("Mairie & service urbanisme (coordonnées)", "texte", "commune",
    "adresse, téléphone, courriel et horaires de la mairie — champ manquant = ABSENT, jamais inventé",
    moteur=None, calcul="passe_plat", fonction="src/labuse/ingestion/mairies.py (bloc MAIRIE)",
    reservoirs=("annuaire_service_public",), portee="live",
    type="texte", table="mairies"),
 "copilote_texte_web": C("Réponse web (Copilote, dernier recours)", "texte", "global",
    "texte libre ≤ 2 phrases MARQUÉ « web » (fait public La Réunion) — jamais un chiffre Sourcé "
    "(garde 2.6), jamais servi sans son marquage",
    moteur=None, calcul="passe_plat", fonction="src/labuse/copilote_v2/outils.py:recherche_web",
    reservoirs=(), portee="live", type="texte", table="(web — aucun réservoir, marquage obligatoire)"),
 # ══ lot 1.5 — les BLOCS de la fiche parcelle jusqu'ici sans id (couverture élargie) ══
 "adresse_ban": C("Adresse", "texte", "parcelle",
    "meilleure adresse BAN rattachée à la parcelle — None si aucune (le front dit « Adresse "
    "non disponible », jamais un champ vide)",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/app.py:_ban_adresse",
    reservoirs=("ban",), portee="live", type="texte",
    table="adresses (id_ban) ⋈ adresse_parcelles"),
 "parcelle_geometrie": C("Géométrie de la parcelle", "classe", "parcelle",
    "le polygone cadastral de la parcelle (contour carte, fiche, PDF) — même table cadastre, "
    "même millésime partout (sonde lot 4.5)",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/app.py (parcels.geom / geom_2975)",
    reservoirs=("cadastre_api_carto",), portee="live", type="geometrie",
    table="parcels.geom (geom_simple pour les tuiles)"),
 "reglement_plu_bloc": C("Règlement de la zone (extraits)", "liste", "parcelle",
    "zones PLU de la parcelle + extraits de règlement calibrés (corpus) — chaque extrait cite "
    "son document",
    moteur="plu_destinations", calcul="moteur",
    fonction="src/labuse/api/app.py:_reglement_plu_block",
    reservoirs=("gpu_plu_api_carto", "sudocuh",), portee="live", type="liste",
    table="parcel_zone_plu + corpus règlements"),
 "historique_permis_liste": C("Sur cette parcelle (permis)", "liste", "parcelle",
    "permis déposés/autorisés sur la parcelle (Sitadel) + caducité — chaque ligne datée",
    moteur="marche_service", calcul="moteur",
    fonction="src/labuse/api/app.py:_historique_site",
    reservoirs=("sitadel",), portee="live", type="liste", table="sitadel_permits"),
 "voisinage_100m_liste": C("Autour, à moins de 100 m", "liste", "parcelle",
    "ventes DVF + permis récents (36 mois) dans le buffer 100 m, site exclu (doctrine M38)",
    moteur="marche_service", calcul="moteur",
    fonction="src/labuse/api/site_voisinage.py:voisinage_proche",
    reservoirs=("dvf", "sitadel",), portee="live", type="liste",
    table="dvf_mutations_parcelle + sitadel_permits (buffer 100 m)"),
 "dvf_parcelle_liste": C("Mutations de la parcelle (DVF)", "liste", "parcelle",
    "dernière mutation de la parcelle + médianes du secteur cadastral (indicateur secondaire, "
    "étiqueté — EXPORTS-1 1.3)",
    moteur="marche_service", calcul="moteur", fonction="src/labuse/api/app.py:_q_v2_fiche (dvf_parcelle)",
    reservoirs=("dvf",), portee="live", type="liste",
    table="v_parcel_dvf_last + dvf_secteur_medianes"),
 "coproprietes_liste": C("Copropriétés (RNIC)", "liste", "parcelle",
    "copropriétés immatriculées rattachées à la parcelle (lots, syndic) — RNIC/ANAH",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/app.py:_q_v2_fiche (coproprietes)",
    reservoirs=("rnic_anah",), portee="live", type="liste", table="rnic_coproprietes"),
 "viabilisation_verdict": C("Viabilisation (faisceau)", "verdict", "parcelle",
    "indicateur de viabilisation par faisceau de preuves (accès, réseaux) + gestionnaires — "
    "jamais un booléen inventé",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/app.py:_viabilisation_block",
    reservoirs=("bd_topo", "rge_alti",), portee="live", type="texte",
    table="parcel_viabilisation (faisceau)"),
 "equipements_proximite_liste": C("À proximité (équipements)", "liste", "parcelle",
    "équipements du quotidien nommés + distance (moteur BPE, couverture partielle DITE)",
    moteur=None, calcul="passe_plat",
    fonction="src/labuse/api/app.py:_proximites_equipements_block",
    reservoirs=("bpe_insee", "osm_overpass",), portee="live", type="liste",
    table="parcel_amenites + spatial_layers (amenite/amenite_bpe)"),
 "evenements_proprietaire_liste": C("Événements propriétaire (BODACC)", "liste", "proprietaire",
    "événements datés du score V (procédures, radiations) — faits publics, chacun sourcé",
    moteur="v_score", calcul="moteur", fonction="src/labuse/api/app.py:_q_v2_fiche (score_v, evenement)",
    reservoirs=("bodacc", "sirene_etablissements",), portee="live", type="liste",
    table="parcel_v_score + bodacc_*"),
 "proprietaire_timeline_liste": C("Historique propriétaire (millésimes PM)", "liste", "proprietaire",
    "timeline unifiée versionné∪servi du fichier PM (2019→2025), diff CONSTAT — servi jamais écrasé",
    moteur="proprietaire_historique", calcul="moteur",
    fonction="src/labuse/proprietaire_historique.py:historique",
    reservoirs=("dgfip_parcelles_pm",), portee="live", type="liste",
    table="pm_proprietaires_millesimes ∪ parcelle_personne_morale"),
 "perimetres_dispositifs_liste": C("Périmètres et dispositifs (parcelle)", "liste", "parcelle",
    "périmètres touchant LA parcelle : QPV, NPNRU/ANRU, bande TVA primo (dérivée), ZFANG/FRR "
    "(commune) — en français, sourcés, jamais un sigle nu",
    moteur=None, calcul="passe_plat", fonction="src/labuse/api/app.py:_territoire_fiscal_block",
    reservoirs=("qpv_2024", "npnru", "zfang", "frr_ex_zrr",), portee="live", type="liste",
    table="spatial_layers (qpv/anru/zfang/frr ; tva_primo dérivé)"),
 # ══ lot 1.8 — ids que les maquettes d'exports attendent (réconciliation exports 05/09) ══
 "surface_vendable_m2": C("Surface vendable (Estimé)", "m²", "parcelle",
    "SHAB vendable du scénario table rase (fourchette du moteur commun) — distincte de "
    "capacite_logements",
    moteur="potentiel", calcul="moteur",
    fonction="src/labuse/faisabilite/potentiel.py:bloc_potentiel (table_rase.vendable_m2)",
    reservoirs=("bd_topo", "cosia", "gpu_plu_api_carto",), portee="run"),
 "surface_plancher_m2": C("Surface de plancher (Estimé)", "m²", "parcelle",
    "surface de plancher du scénario table rase (moteur commun) — distincte de capacite_logements",
    moteur="potentiel", calcul="moteur",
    fonction="src/labuse/faisabilite/potentiel.py:bloc_potentiel (table_rase.plancher_m2)",
    reservoirs=("bd_topo", "cosia", "gpu_plu_api_carto",), portee="run"),
 "marge_surelevation_m": C("Marge de surélévation (à l'égout)", "m", "parcelle",
    "hauteur restante sous la règle de hauteur à l'égout de la zone (moteur commun, EXPORTS-1 3.2)",
    moteur="potentiel", calcul="moteur",
    fonction="src/labuse/faisabilite/potentiel.py:surelevation",
    reservoirs=("bd_topo", "gpu_plu_api_carto",), portee="run"),
 "part_logements_egout_pct": C("Logements raccordés à l'égout", "%", "parcelle",
    "part des logements raccordés au tout-à-l'égout (INSEE RP2022 EGOUL, maille IRIS, repli "
    "commune) — le TAUX, jamais un verdict",
    moteur="anc", calcul="moteur",
    fonction="src/labuse/anc_service.py:statut_anc (producteur nommé, délégation)",
    reservoirs=("insee_rp2022_egoul",), portee="live"),
 "ventes_retenues_n": C("Ventes retenues (nuage)", "nombre", "parcelle",
    "ventes DVF retenues par le filtre de comparables (couverture VISIBLE — EXPORTS-1 lot 2)",
    moteur="marche_service", calcul="moteur",
    fonction="src/labuse/marche_service.py:filtre_ventes",
    reservoirs=("dvf",), portee="live"),
 "ventes_ecartees_n": C("Ventes écartées (nuage)", "nombre", "parcelle",
    "ventes DVF écartées par le filtre de comparables, avec motif (couverture visible)",
    moteur="marche_service", calcul="moteur",
    fonction="src/labuse/marche_service.py:filtre_ventes",
    reservoirs=("dvf",), portee="live"),
 "bilan_ca_eur": C("Chiffre d'affaires (bilan)", "€", "parcelle",
    "CA = surface vendable × prix de sortie neuf observé (bilan à rebours)",
    moteur="bilan_promoteur", calcul="moteur",
    fonction="src/labuse/faisabilite/bilan.py:compute_bilan (ca)",
    reservoirs=("dvf",), portee="live"),
 "bilan_cout_construction_eur": C("Coût de construction (bilan)", "€", "parcelle",
    "SDP × coût au m² (calibré secteur ou fourchette YAML), majoration pluviale comprise",
    moteur="bilan_promoteur", calcul="moteur",
    fonction="src/labuse/faisabilite/bilan.py:compute_bilan (cout_construction)",
    reservoirs=(), portee="live"),
 "bilan_vrd_eur": C("VRD (bilan)", "€", "parcelle",
    "VRD base × surface terrain, majorations pente/assainissement (bilan_params par secteur)",
    moteur="bilan_promoteur", calcul="moteur",
    fonction="src/labuse/faisabilite/bilan.py:compute_bilan (cout_vrd)",
    reservoirs=("rge_alti",), portee="live"),
 "bilan_marge_eur": C("Marge (bilan)", "€", "parcelle",
    "marge cible en % du CA (hypothèse déclarée, jamais cachée)",
    moteur="bilan_promoteur", calcul="moteur",
    fonction="src/labuse/faisabilite/bilan.py:compute_bilan (marge)",
    reservoirs=(), portee="live"),
 "bilan_frais_eur": C("Honoraires & frais (bilan)", "€", "parcelle",
    "honoraires + frais financiers en % (bilan_params par secteur, hypothèses affichées)",
    moteur="bilan_promoteur", calcul="moteur",
    fonction="src/labuse/faisabilite/bilan.py:compute_bilan (frais)",
    reservoirs=(), portee="live"),
 "ecart_prix_demande_pct": C("Écart au prix demandé", "%", "parcelle",
    "charge foncière supportable vs prix demandé SAISI (verdict d'achat de la calculette) — "
    "n'existe que si le client a saisi un prix",
    moteur="bilan_promoteur", calcul="moteur",
    fonction="src/labuse/faisabilite/bilan.py:compute_calculette (verdict d'achat)",
    reservoirs=(), portee="projet"),
 "bilan_demolition_eur": C("Démolition (bilan)", "€", "parcelle",
    "poste démolition du bilan à rebours — saisi par le client (le moteur ne l'estime pas)",
    moteur="bilan_promoteur", calcul="moteur",
    fonction="src/labuse/faisabilite/bilan.py (poste à câbler)",
    reservoirs=(), portee="projet",
    en_attente="maquettes d'exports — poste servi au chantier EXPORTS (Financier)"),
 "sensibilite_cout_construction": C("Sensibilité au coût de construction", "%", "parcelle",
    "variation de la charge foncière pour ±10 % de coût de construction (tableau de sensibilité)",
    moteur="bilan_promoteur", calcul="moteur",
    fonction="src/labuse/faisabilite/bilan.py (dérivable de compute_calculette)",
    reservoirs=(), portee="live",
    en_attente="maquettes d'exports — servie au chantier EXPORTS (Financier)"),
 "emprise_batie_m2": C("Emprise bâtie", "m²", "parcelle",
    "emprise au sol du bâti de la parcelle (BD TOPO + CoSIA)",
    moteur="bati_revele", calcul="moteur",
    fonction="src/labuse/faisabilite/bati_revele.py:build_parcel_bati_revele "
             "(producteur nommé, délégation)",
    reservoirs=("bd_topo", "cosia",), portee="run",
    en_attente="maquettes d'exports — servie au chantier EXPORTS"),
 "hauteur_bati_m": C("Hauteur du bâti", "m", "parcelle",
    "hauteur du bâti principal (BD TOPO, médiane des bâtiments intersectants)",
    moteur="potentiel", calcul="moteur",
    fonction="src/labuse/faisabilite/potentiel.py:_hauteur_bati_m",
    reservoirs=("bd_topo",), portee="live",
    en_attente="maquettes d'exports — servie au chantier EXPORTS"),
 "n_batiments": C("Nombre de bâtiments", "nombre", "parcelle",
    "compte des bâtiments de la parcelle (BD TOPO + CoSIA)",
    moteur="bati_revele", calcul="moteur",
    fonction="src/labuse/faisabilite/bati_revele.py:build_parcel_bati_revele "
             "(producteur nommé, délégation)",
    reservoirs=("bd_topo", "cosia",), portee="run",
    en_attente="maquettes d'exports — servie au chantier EXPORTS"),
 # réglementaires nouvelles : DÉCLARÉES ici, réservoirs par CIRCUIT-3 lot 6 (mandat 1.8)
 "er_emplacement_reserve": C("Emplacement réservé (ER)", "classe", "parcelle",
    "la parcelle est-elle grevée d'un emplacement réservé du PLU (destination, bénéficiaire)",
    moteur=None, calcul="passe_plat", fonction="(réservoir à venir — GPU prescriptions)",
    reservoirs=(), portee="live", type="classe",
    domaine=("grevee", "non_grevee"), domaine_source="prescriptions surfaciques du GPU",
    en_attente="réservoir CIRCUIT-3 lot 6"),
 "ebc_classe": C("Espace boisé classé (EBC)", "classe", "parcelle",
    "la parcelle intersecte-t-elle un espace boisé classé du PLU",
    moteur=None, calcul="passe_plat", fonction="(réservoir à venir — GPU prescriptions)",
    reservoirs=(), portee="live", type="classe",
    domaine=("intersecte", "hors"), domaine_source="prescriptions surfaciques du GPU",
    en_attente="réservoir CIRCUIT-3 lot 6"),
 "dpu_perimetre": C("Droit de préemption urbain (DPU)", "classe", "parcelle",
    "la parcelle est-elle dans un périmètre de préemption (DPU simple/renforcé)",
    moteur=None, calcul="passe_plat", fonction="(réservoir à venir — GPU / délibérations)",
    reservoirs=(), portee="live", type="classe",
    domaine=("simple", "renforce", "hors"), domaine_source="périmètres DPU (GPU/délibérations)",
    en_attente="réservoir CIRCUIT-3 lot 6"),
 "peb_zone": C("Plan d'exposition au bruit (PEB)", "classe", "parcelle",
    "zone PEB de l'aérodrome (A/B/C/D) si la parcelle y est",
    moteur=None, calcul="passe_plat", fonction="(réservoir à venir — PEB Roland-Garros/Pierrefonds)",
    reservoirs=(), portee="live", type="classe",
    domaine=("A", "B", "C", "D", "hors"), domaine_source="zones du PEB (arrêté préfectoral)",
    en_attente="réservoir CIRCUIT-3 lot 6"),
 "zonage_abc_logement": C("Zonage A/B/C (logement)", "classe", "commune",
    "zone A/B/C du dispositif d'investissement locatif pour la commune",
    moteur=None, calcul="passe_plat", fonction="(réservoir à venir — arrêté zonage ABC)",
    reservoirs=(), portee="live", type="classe",
    domaine=("A", "B1", "B2", "C"), domaine_source="arrêté de zonage A/B/C (logement)",
    en_attente="réservoir CIRCUIT-3 lot 6"),
}

#: 1.1 — le type des déclarations « auto » est dérivé de l'unité (les entrées historiques de
#: CIRCUIT-1 restent des littéraux inchangés ; les nouvelles déclarations posent `type=`).
DONNEES = {cid: (replace(d, type=_TYPE_PAR_UNITE.get(d.unite, "nombre")) if d.type == "auto" else d)
           for cid, d in DONNEES.items()}

#: rétro-compatibilité CIRCUIT-1 — le registre des chiffres EST le registre des données
CHIFFRES = DONNEES

#: 0-bis (scission du neuf, transition UN lot puis retrait) : l'ancien id `prix_neuf_vefa_eur_m2`
#: recouvrait DEUX définitions (VEFA à l'acte 5 003 €/m² vs neuf observé 4 730 €/m² à Saint-Paul —
#: fuite mesurée de CIRCUIT-0, soldée par scission). Tout lecteur de l'ancien id résout vers le
#: VEFA à l'acte ; le neuf observé a SON id. À RETIRER au prochain lot.
ALIAS_TRANSITION: dict[str, str] = {"prix_neuf_vefa_eur_m2": "prix_neuf_vefa_acte_eur_m2"}


def resoudre(chiffre_id: str) -> str:
    """Résout un id d'alias de transition vers l'id canonique (identité sinon)."""
    return ALIAS_TRANSITION.get(chiffre_id, chiffre_id)
