"""CIRCUIT-1 lot 1.2/1.3 — LE REGISTRE DES ROBINETS : les 122 endroits qui affichent au moins
un chiffre (ids de robinets.csv, CIRCUIT-0), chacun avec sa catégorie, son parent, sa route,
son mode de rendu et LA LISTE DES CHIFFRES qu'il sert (ids de chiffres.py). Le graphe
réservoir → chiffre → robinet est DÉRIVÉ (cf. __init__.aretes), jamais saisi deux fois.

`hors_registre` (lot 1.3) : ce que le robinet montre n'est PAS un chiffre (tuiles, géométries,
classes réglementaires passe-plat, textes, coordonnées) — la raison est déclarée ici même.
"""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Robinet:
    categorie: str      # fond · couche · outil · fiche · copilote · veille · projets · crm ·
                        # notification · pdf · page_client · admin
    nom: str            # libellé exact de l'écran
    parent: str | None
    route: str          # endpoint API, template, builder PDF, template Brevo
    mode_rendu: str     # template_serveur · json_puis_js · pdf · mail · texte_llm · tuiles
    chiffres: tuple[str, ...] = field(default_factory=tuple)
    hors_registre: str | None = None    # raison si le robinet n'affiche aucun chiffre


R = Robinet


def _r(categorie, nom, parent, route, mode_rendu, chiffres=(), hors_registre=None):
    return Robinet(categorie, nom, parent, route, mode_rendu, tuple(chiffres), hors_registre)


ROBINETS: dict[str, Robinet] = {
 "fond_plan_ign": _r("fond", "Plan IGN v2", None,
    "WMTS GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2", "tuiles", chiffres=("tuiles_plan_ign",)),
 "fond_ortho_actuelle": _r("fond", "Actuelle · Ortho Express 2025", None,
    "WMTS ORTHOIMAGERY.ORTHOPHOTOS.ORTHO-EXPRESS.2025", "tuiles", chiffres=("tuiles_ortho_2025",)),
 "fond_ortho_1950": _r("fond", "1950-1965", None,
    "WMTS ORTHOIMAGERY.ORTHOPHOTOS.1950-1965", "tuiles", chiffres=("tuiles_ortho_1950_1965",)),
 "fond_ortho_2000": _r("fond", "2000-2005", None,
    "WMTS ORTHOIMAGERY.ORTHOPHOTOS2000-2005", "tuiles", chiffres=("tuiles_ortho_2000_2005",)),
 "fond_ortho_2006": _r("fond", "2006-2010", None,
    "WMTS ORTHOIMAGERY.ORTHOPHOTOS2006-2010", "tuiles", chiffres=("tuiles_ortho_2006_2010",)),
 "fond_ortho_2011": _r("fond", "2011-2015", None,
    "WMTS ORTHOIMAGERY.ORTHOPHOTOS2011-2015", "tuiles", chiffres=("tuiles_ortho_2011_2015",)),
 "fond_ortho_2016": _r("fond", "2016-2020", None,
    "WMTS ORTHOIMAGERY.ORTHOPHOTOS2016-2020", "tuiles", chiffres=("tuiles_ortho_2016_2020",)),
 "fond_ortho_2021": _r("fond", "2021-2023", None,
    "WMTS ORTHOIMAGERY.ORTHOPHOTOS2021-2023", "tuiles", chiffres=("tuiles_ortho_2021_2023",)),
 "fond_sombre": _r("fond", "Sombre", None,
    "canvas + couches", "json_puis_js", chiffres=(), hors_registre="décor : mode de rendu (canvas), aucune source externe"),
 "fond_clair": _r("fond", "Clair", None,
    "canvas + couches", "json_puis_js", chiffres=(), hors_registre="décor : mode de rendu (canvas), aucune source externe"),
 "couche_verdict": _r("couche", "Verdict · Classement servi", None,
    "tuiles MVT (run servi)", "tuiles", chiffres=("tier_opportunite", "verdict_couche",)),
 "couche_zonage_plu": _r("couche", "Zonage PLU (par type)", None,
    "/map/layers.geojson?kind=plu_gpu_zone", "json_puis_js", chiffres=("zone_plu_famille", "zonage_plu_couche",)),
 "couche_gpu_brut": _r("couche", "Limites officielles PLU (GPU brut)", None,
    "/map/layers.geojson?kind=plu_gpu", "json_puis_js", chiffres=("gpu_brut_couche",)),
 "couche_cinquante_pas": _r("couche", "50 pas géométriques", None,
    "/map/layers.geojson?kind=cinquante_pas", "json_puis_js", chiffres=("cinquante_pas_couche",)),
 "couche_znieff": _r("couche", "ZNIEFF — type I & II", None,
    "/map/layers.geojson?kind=znieff", "json_puis_js", chiffres=("znieff_couche",)),
 "couche_bpe": _r("couche", "Équipements (INSEE BPE)", None,
    "/map/layers.geojson?kind=amenite_bpe", "json_puis_js", chiffres=("bpe_couche",)),
 "couche_alea_inondation": _r("couche", "Aléa inondation", None,
    "/map/layers.geojson?kind=georisque_alea", "json_puis_js", chiffres=("alea_inondation_couche",)),
 "couche_alea_mvt": _r("couche", "Aléa mouvement de terrain", None,
    "/map/layers.geojson?kind=georisque_alea", "json_puis_js", chiffres=("alea_mvt_couche",)),
 "couche_transport": _r("couche", "Transport public", None,
    "/map/layers.geojson?kind=transport_ligne,transport_arret", "json_puis_js", chiffres=("transport_couche",)),
 "couche_axes": _r("couche", "Axes structurants", None,
    "/map/layers.geojson?kind=axe_structurant,pole_echange", "json_puis_js", chiffres=("axes_couche",)),
 "couche_lignes_ht": _r("couche", "Lignes haute tension", None,
    "/map/layers.geojson?kind=ligne_ht", "json_puis_js", chiffres=("lignes_ht_couche",)),
 "couche_tcsp": _r("couche", "Axe de transport structurant", None,
    "/map/layers.geojson?kind=tcsp_axe", "json_puis_js", chiffres=("tcsp_couche",)),
 "couche_dispositifs": _r("couche", "Dispositifs et périmètres", None,
    "/map/layers.geojson?kind=qpv,tva_primo,anru,zfang,frr", "json_puis_js", chiffres=("dispositifs_couche",)),
 "couche_vefa": _r("couche", "Prix du logement neuf (VEFA)", None,
    "/map/layers.geojson?kind=vefa_neuf", "json_puis_js", chiffres=("tranche_prix_vefa", "vefa_couche",)),
 "couche_densifier": _r("couche", "Densifier l'existant", None,
    "/map/layers.geojson (résiduel)", "json_puis_js", chiffres=("classe_residuel", "densifier_couche",)),
 "couche_ppr": _r("couche", "PPR multirisque", None,
    "/map/layers.geojson?kind=ppr", "json_puis_js", chiffres=("ppr_couche",)),
 "couche_parc_national": _r("couche", "Parc national", None,
    "/map/layers.geojson?kind=parc_national", "json_puis_js", chiffres=("parc_national_couche",)),
 "couche_limites_parcelles": _r("couche", "Limites parcelles", None,
    "tuiles MVT (contours)", "tuiles", chiffres=("limites_parcelles_couche",)),
 "couche_communes": _r("couche", "Limites communes", None,
    "contours embarqués (seed)", "json_puis_js", chiffres=("communes_couche",)),
 "couche_equip_osm": _r("couche", "Équipements (OSM)", None,
    "/map/layers.geojson?kind=amenite", "json_puis_js", chiffres=("equip_osm_couche",)),
 "outil_etudier_bien": _r("outil", "Étudier un bien", None,
    "/modules/scoreur-adresse", "json_puis_js", chiffres=("tier_opportunite", "surface_parcelle_m2",)),
 "outil_faisabilite": _r("outil", "Faisabilité", None,
    "/modules/faisabilite/{idu}", "json_puis_js", chiffres=("capacite_logements", "sdp_residuelle_m2", "charge_fonciere_eur", "cout_construction_saisi_eur_m2", "marge_frais_saisie_pct", "prix_demande_saisi_eur", "ecart_prix_demande_pct",)),
 "outil_taxe_amenagement": _r("outil", "Taxe d'aménagement", None,
    "/modules/taxe-amenagement", "json_puis_js", chiffres=("taxe_amenagement_eur",)),
 "outil_pieges": _r("outil", "Pièges et risques", None,
    "/modules/risques", "json_puis_js", chiffres=("n_vigilances",)),
 "outil_plu": _r("outil", "PLU", None,
    "/modules/plu-annuaire", "json_puis_js", chiffres=("n_extraits_plu", "n_communes_rnu",)),
 "outil_plu_procedure": _r("outil", "Procédure & changement", "outil_plu",
    "/moteurs/simulplu/procedures", "json_puis_js", chiffres=("n_procedures_plu",)),
 "outil_plu_simuler": _r("outil", "Simuler un changement", "outil_plu",
    "/moteurs/simulplu/zones", "json_puis_js", chiffres=("simulplu_resultat",)),
 "outil_comparer_parcelles": _r("outil", "Comparer des parcelles", None,
    "/comparateur-communes", "json_puis_js", chiffres=("comparateur_composite", "stock_opportunites", "velocite_delai_median_mois", "permis_5a_n", "deficit_sru_pts", "pression_zan_ha", "prix_neuf_vefa_acte_eur_m2", "prix_ancien_median_eur_m2",)),
 "outil_assemblage": _r("outil", "Assemblage", None,
    "/moteurs/assemblage", "json_puis_js", chiffres=("assemblage_parcelles_n", "assemblage_surface_m2",)),
 "outil_scan_patrimoine": _r("outil", "Scan patrimoine", None,
    "/modules/patrimoine", "json_puis_js", chiffres=("n_parcelles_pm", "dirigeant_pm_signal",)),
 "outil_scan_possede": _r("outil", "Possède", "outil_scan_patrimoine",
    "/modules/patrimoine?siren=…", "json_puis_js", chiffres=("n_parcelles_pm",)),
 "outil_scan_construit": _r("outil", "Ce qu'ils construisent", "outil_scan_patrimoine",
    "/modules/patrimoine + permis", "json_puis_js", chiffres=("n_parcelles_pm", "permis_12m_n",)),
 "outil_courrier": _r("outil", "Courrier propriétaire", None,
    "/modules/courriers", "json_puis_js", chiffres=("courrier_demandes_n",)),
 "outil_prospection_solaire": _r("outil", "Prospection solaire", None,
    "/modules/prospection-solaire", "json_puis_js", chiffres=("prod_spec_kwh_kwc", "azimut_bati_deg",)),
 "outil_solaire_toits": _r("outil", "Toits bien exposés", "outil_prospection_solaire",
    "/modules/prospection-solaire", "json_puis_js", chiffres=("prod_spec_kwh_kwc", "azimut_bati_deg",)),
 "outil_solaire_piscines": _r("outil", "Piscines", "outil_prospection_solaire",
    "/modules/prospection-piscines", "json_puis_js", chiffres=("n_piscines",)),
 "outil_communes": _r("outil", "Communes", None,
    "/communes", "json_puis_js", chiffres=("prix_ancien_median_eur_m2", "prix_neuf_vefa_acte_eur_m2", "stock_opportunites", "velocite_delai_median_mois", "deficit_sru_pts",)),
 "outil_communes_comparaison": _r("outil", "Comparaison communes", "outil_communes",
    "/comparateur-communes", "json_puis_js", chiffres=("comparateur_composite", "stock_opportunites", "velocite_delai_median_mois", "permis_5a_n", "deficit_sru_pts", "pression_zan_ha", "prix_neuf_vefa_acte_eur_m2", "prix_ancien_median_eur_m2",)),
 "outil_communes_evolution": _r("outil", "Évolution du marché", "outil_communes",
    "/moteurs/barometre", "json_puis_js", chiffres=("prix_ancien_median_eur_m2", "mutations_12m_n",)),
 "outil_communes_acquisitions": _r("outil", "Acquisitions récentes", "outil_communes",
    "/communes/{commune}/acquisitions-pm", "json_puis_js", chiffres=("acquisitions_pm_n",)),
 "outil_permis": _r("outil", "Permis", None,
    "/modules/permis", "json_puis_js", chiffres=("permis_12m_n", "velocite_delai_median_mois",)),
 "outil_permis_radar": _r("outil", "Radar permis", "outil_permis",
    "/modules/permis", "json_puis_js", chiffres=("permis_12m_n", "velocite_delai_median_mois",)),
 "outil_permis_point_mort": _r("outil", "Permis au point mort", "outil_permis",
    "/modules/promesses", "json_puis_js", chiffres=("point_mort_n",)),
 "outil_densifier": _r("outil", "Densifier l'existant", None,
    "/modules/renouvellement", "json_puis_js", chiffres=("n_densifiables", "sdp_residuelle_m2",)),
 "outil_etude_zone": _r("outil", "Étude de zone", None,
    "/modules/etude-zone", "json_puis_js", chiffres=("population_zone", "n_concurrents_zone", "emplois_fourchette", "revenu_approche_eur", "trafic_mja",)),
 "outil_remonter_temps": _r("outil", "Remonter le temps", None,
    "/ortho?an=…", "json_puis_js", chiffres=("annee_ortho",)),
 "outil_radar_client": _r("outil", "Radar", None,
    "/radar/biens", "json_puis_js", chiffres=("annonces_actives_n", "prix_demande_median_eur_m2",)),
 "outil_radar_marche": _r("outil", "Marché", "outil_radar_client",
    "/radar/marche", "json_puis_js", chiffres=("annonces_actives_n", "prix_demande_median_eur_m2", "delai_vente_median_j", "ecart_demande_acte_pct",)),
 "fiche_parcelle_entete": _r("fiche", "En-tête (adresse, géométrie)", "fiche_parcelle",
    "/parcels/{idu}", "json_puis_js", chiffres=("adresse_ban", "parcelle_geometrie",)),
 "fiche_parcelle_urbanisme": _r("fiche", "Règlement d'urbanisme (zones + extraits)", "fiche_parcelle",
    "/parcels/{idu}", "json_puis_js", chiffres=("reglement_plu_bloc", "zone_plu_famille",)),
 "fiche_parcelle_dispositifs": _r("fiche", "Dispositifs et périmètres (QPV, ANRU, ZFANG, FRR)", "fiche_parcelle",
    "/parcels/{idu}", "json_puis_js", chiffres=("perimetres_dispositifs_liste",)),
 "fiche_parcelle_score": _r("fiche", "Score d'opportunité (tier)", "fiche_parcelle",
    "/parcels/{idu}", "json_puis_js", chiffres=("tier_opportunite", "rang_tier",)),
 "fiche_parcelle_constructibilite": _r("fiche", "Constructibilité", "fiche_parcelle",
    "/parcels/{idu}", "json_puis_js", chiffres=("capacite_logements", "sdp_residuelle_m2", "charge_fonciere_eur", "potentiel_verdict", "prix_neuf_observe_eur_m2", "mixite_clause", "surface_vendable_m2", "surface_plancher_m2", "marge_surelevation_m",)),
 "fiche_parcelle_le_bien": _r("fiche", "Le bien", "fiche_parcelle",
    "/parcels/{idu}", "json_puis_js", chiffres=("emprise_batie_m2", "hauteur_bati_m", "n_batiments", "surface_libre_sol_m2", "nature_toit", "pente_toit_deg",)),
 "fiche_parcelle_risques": _r("fiche", "Risques et protections", "fiche_parcelle",
    "/parcels/{idu}", "json_puis_js", chiffres=("n_vigilances",)),
 "fiche_parcelle_marche": _r("fiche", "Marché et secteur", "fiche_parcelle",
    "/parcels/{idu}", "json_puis_js", chiffres=("prix_terrain_secteur_eur_m2", "prix_sortie_bati_eur_m2", "ventes_100m_n", "ventes_retenues_n", "ventes_ecartees_n", "dvf_parcelle_liste", "parc_social_rpls_logements",)),
 "fiche_parcelle_reseaux": _r("fiche", "Réseaux et accès", "fiche_parcelle",
    "/parcels/{idu}", "json_puis_js", chiffres=("pente_deg", "piscine_m2", "distance_arret_m", "part_logements_egout_pct", "viabilisation_verdict",)),
 "fiche_parcelle_autour": _r("fiche", "Autour de cette parcelle", "fiche_parcelle",
    "/parcels/{idu} + /parcels/{idu}/zone", "json_puis_js", chiffres=("population_zone", "n_permis_proximite", "depots_secteur_n", "historique_permis_liste", "voisinage_100m_liste", "equipements_proximite_liste",)),
 "fiche_parcelle_proprietaire": _r("fiche", "Propriétaire", "fiche_parcelle",
    "/parcels/{idu}", "json_puis_js", chiffres=("type_proprietaire", "proprietaire_timeline_liste", "evenements_proprietaire_liste",)),
 "fiche_parcelle_confiance": _r("fiche", "Confiance données", "fiche_parcelle",
    "/parcels/{idu}", "json_puis_js", chiffres=("verdict_icd",)),
 "fiche_parcelle_solaire": _r("fiche", "Solaire (rosace, productible)", "fiche_parcelle",
    "/parcels/{idu}", "json_puis_js", chiffres=("prod_spec_kwh_kwc",)),
 "fiche_parcelle_division": _r("fiche", "Division (copropriétés/lots)", "fiche_parcelle",
    "/parcels/{idu}", "json_puis_js", chiffres=("divisible_classe", "coproprietes_liste",)),
 "fiche_commune_regles_urbanisme": _r("fiche", "Règles d'urbanisme", "fiche_commune",
    "/communes/{c}/contexte", "json_puis_js", chiffres=("statut_plu",)),
 "fiche_commune_zan": _r("fiche", "Enveloppe ZAN", "fiche_commune",
    "/communes/{c}/contexte", "json_puis_js", chiffres=("zan_reste_ha",)),
 "fiche_commune_sru": _r("fiche", "Logement social — SRU", "fiche_commune",
    "/communes/{c}/contexte", "json_puis_js", chiffres=("taux_lls_pct", "deficit_sru_pts",)),
 "fiche_commune_permis": _r("fiche", "Permis & délais", "fiche_commune",
    "/communes/{c}/contexte", "json_puis_js", chiffres=("permis_12m_n", "velocite_delai_median_mois", "point_mort_n",)),
 "fiche_commune_plh": _r("fiche", "Programme local — PLH", "fiche_commune",
    "/communes/{c}/contexte", "json_puis_js", chiffres=("plh_objectif_logements_an",)),
 "fiche_commune_prix": _r("fiche", "Prix & tendance", "fiche_commune",
    "/communes/{c}/contexte", "json_puis_js", chiffres=("prix_ancien_median_eur_m2", "prix_neuf_vefa_acte_eur_m2", "mutations_12m_n",)),
 "fiche_commune_terrain_nu": _r("fiche", "Terrain nu", "fiche_commune",
    "/communes/{c}/contexte", "json_puis_js", chiffres=("prix_terrain_zone_eur_m2",)),
 "fiche_commune_annonces": _r("fiche", "Annonces en cours — Radar", "fiche_commune",
    "/communes/{c}/contexte", "json_puis_js", chiffres=("annonces_actives_n", "prix_demande_median_eur_m2", "ecart_demande_acte_pct",)),
 "fiche_commune_loyers": _r("fiche", "Loyers", "fiche_commune",
    "/communes/{c}/contexte", "json_puis_js", chiffres=("loyer_median_eur_m2",)),
 "fiche_commune_foncier": _r("fiche", "Foncier repéré", "fiche_commune",
    "/communes/{c}/contexte", "json_puis_js", chiffres=("n_parcelles_commune", "stock_opportunites", "n_densifiables",)),
 "fiche_commune_zonage": _r("fiche", "Zonage", "fiche_commune",
    "/communes/{c}/contexte", "json_puis_js", chiffres=("part_zone_U_pct", "part_zone_AU_pct", "part_zone_A_pct", "part_zone_N_pct",)),
 "fiche_commune_risques": _r("fiche", "Risques", "fiche_commune",
    "/communes/{c}/contexte", "json_puis_js", chiffres=("ppr_pct", "catnat_n",)),
 "fiche_commune_population": _r("fiche", "Population & logement", "fiche_commune",
    "/communes/{c}/contexte", "json_puis_js",
    chiffres=("habitants_n", "vacance_pct", "autres_loges_pct")),
 "fiche_commune_qpv": _r("fiche", "Quartiers prioritaires", "fiche_commune",
    "/communes/{c}/contexte", "json_puis_js", chiffres=("qpv_n",)),
 "fiche_commune_mairie": _r("fiche", "Mairie & service urbanisme", "fiche_commune",
    "/communes/{c}/contexte", "json_puis_js", chiffres=("mairie_coordonnees",)),
 "fiche_annonce": _r("fiche", "Fiche bien (Radar)", None,
    "/radar/biens/{id}", "json_puis_js", chiffres=("prix_demande_eur", "prix_demande_median_eur_m2",)),
 "fiche_proprietaire": _r("fiche", "Fiche propriétaire (timeline PM)", None,
    "/parcels/{idu} (bloc) + patrimoine", "json_puis_js", chiffres=("n_parcelles_pm",)),
 "fiche_soleil": _r("fiche", "Fiche soleil (photo toit + rosace)", None,
    "/modules/prospection-solaire (détail)", "json_puis_js", chiffres=("prod_spec_kwh_kwc",)),
 "copilote_compter_parcelles": _r("copilote", "Compter des parcelles", "copilote",
    "/api/copilote-v2/ask", "texte_llm", chiffres=("copilote_compte_parcelles",)),
 "copilote_compter_permis": _r("copilote", "Nombre de permis accordés", "copilote",
    "/api/copilote-v2/ask", "texte_llm", chiffres=("permis_12m_n",)),
 "copilote_parcelles_entreprise": _r("copilote", "Parcelles détenues par une personne morale", "copilote",
    "/api/copilote-v2/ask", "texte_llm", chiffres=("n_parcelles_pm",)),
 "copilote_fiche_parcelle": _r("copilote", "Données d'une parcelle (IDU)", "copilote",
    "/api/copilote-v2/ask", "texte_llm", chiffres=("surface_parcelle_m2",)),
 "copilote_stats_commune": _r("copilote", "Contexte d'une commune (SRU, marché)", "copilote",
    "/api/copilote-v2/ask", "texte_llm", chiffres=("taux_lls_pct",)),
 "copilote_delais_instruction": _r("copilote", "Délai médian d'instruction (commune)", "copilote",
    "/api/copilote-v2/ask", "texte_llm", chiffres=("velocite_delai_median_mois",)),
 "copilote_marche": _r("copilote", "Marché immobilier d'une commune", "copilote",
    "/api/copilote-v2/ask", "texte_llm", chiffres=("prix_ancien_median_eur_m2",)),
 "copilote_compter_piscines": _r("copilote", "Compter les piscines détectées", "copilote",
    "/api/copilote-v2/ask", "texte_llm", chiffres=("n_piscines",)),
 "copilote_destination_zone": _r("copilote", "Peut-on ouvrir une activité sur cette parcelle ?", "copilote",
    "/api/copilote-v2/ask", "texte_llm", chiffres=("destination_statut",)),
 "copilote_recherche_web": _r("copilote", "Dernier recours — fait public La Réunion", "copilote",
    "/api/copilote-v2/ask", "texte_llm", chiffres=("copilote_texte_web",)),
 "veille_evaluations": _r("veille", "Veilles (critères + déclenchements)", None,
    "/copilote-v2/veilles", "json_puis_js", chiffres=("n_veilles",)),
 "projets_liste": _r("projets", "Projets (cadrage · retenues · vivier)", None,
    "/projets", "json_puis_js", chiffres=("projet_cadrage_n", "projet_retenues_n",)),
 "projets_compteur": _r("projets", "Bandeau d'analyse (compteur projet)", "projets_liste",
    "/projets/compteur", "json_puis_js", chiffres=("projet_cadrage_n",)),
 "crm_kanban": _r("crm", "Pipeline (kanban, cartes par colonne)", None,
    "/pipeline/columns", "json_puis_js", chiffres=("crm_cartes_n",)),
 "crm_retour_terrain": _r("crm", "Retour terrain (étiquettes de contact)", "crm_kanban",
    "/pipeline", "json_puis_js", chiffres=("pipeline_entrees_n",)),
 "notif_cloche": _r("notification", "Cloche (événements)", None,
    "/events", "json_puis_js", chiffres=("n_notifications",)),
 "notif_brief_matin": _r("notification", "Brief du matin", None,
    "/brief", "json_puis_js", chiffres=("n_bascules_7j",)),
 "notif_digest_quotidien": _r("notification", "Digest quotidien (mail)", None,
    "envoyer_digests (CLI digest)", "mail", chiffres=("n_biens_du_jour",)),
 "notif_radar_digest": _r("notification", "Radar — digest quotidien (Brevo ID 12)", None,
    "template Brevo 12 (PRENOM·DATE·NB_BIENS·LIEN_RADAR·CARTES)", "mail", chiffres=("n_biens_du_jour",)),
 "notif_radar_alerte": _r("notification", "Radar — alerte de veille (Brevo ID 13)", None,
    "template Brevo 13 (PRENOM·VEILLE·NB_BIENS·CRITERES·CARTES·LIEN_RADAR·LIEN_VEILLE)", "mail", chiffres=("n_biens_veille",)),
 "pdf_flash": _r("pdf", "Rapport Flash", None,
    "/flash/telecharger (TEMPLATE_VERSION 1.4, WeasyPrint)", "pdf", chiffres=("tier_opportunite", "prix_terrain_secteur_eur_m2", "population_zone",)),
 "pdf_dossier_expert": _r("pdf", "Dossier parcelle", None,
    "/dossier/{idu}.pdf (quota mensuel)", "pdf", chiffres=("tier_opportunite", "potentiel_verdict", "sdp_residuelle_m2", "surface_vendable_m2",)),
 "pdf_banquier": _r("pdf", "Dossier banquier", None,
    "/dossier-banquier/{idu}.pdf", "pdf", chiffres=("charge_fonciere_eur", "prix_terrain_secteur_eur_m2", "prix_neuf_observe_eur_m2", "mixite_clause", "bilan_ca_eur", "bilan_cout_construction_eur", "bilan_vrd_eur", "bilan_marge_eur", "bilan_frais_eur",)),
 "pdf_pre_dossier_pc": _r("pdf", "Pré-dossier PC (ZIP CERFA 13406*17)", None,
    "/pre-dossier/zip", "pdf", chiffres=("zone_plu_famille", "zonage_plu_couche",)),
 "pdf_lettre_zonage": _r("pdf", "Lettre de zonage", None,
    "/pdf (courrier)", "pdf", chiffres=("zone_plu_famille", "zonage_plu_couche",)),
 "pdf_argumentaire": _r("pdf", "Argumentaire", None,
    "/argumentaire", "pdf", chiffres=("prix_terrain_secteur_eur_m2",)),
 "page_accueil_chiffres": _r("page_client", "Accueil — bloc chiffres", None,
    "/accueil/chiffres (cache 1 h)", "json_puis_js", chiffres=("n_parcelles_ile", "n_sources", "run_label_servi",)),
 "page_accueil_semaine": _r("page_client", "Accueil — cette semaine", None,
    "/accueil/cette-semaine", "json_puis_js", chiffres=("n_bascules_7j",)),
 "page_sources_client": _r("page_client", "Sources de données", None,
    "/sources", "json_puis_js", chiffres=("n_sources",)),
 "page_sources_couverture": _r("page_client", "Couverture des sources", None,
    "/sources/couverture", "json_puis_js", chiffres=("couverture_commune_pct",)),
 "page_flash_publique": _r("page_client", "/flash (formulaire public)", None,
    "/flash (GET/POST) + /flash/statut", "template_serveur", chiffres=("prix_flash_eur",)),
 "admin_pilotage": _r("admin", "Pilotage (KPI à faire / à jour)", None,
    "/admin/pilotage", "json_puis_js", chiffres=("n_a_faire",)),
 "admin_catalogue_sources": _r("admin", "Données › Catalogue (sources)", "admin_donnees",
    "/admin/sources", "json_puis_js", chiffres=("n_sources",)),
 "admin_flux_circuit": _r("admin", "Données › Circuit (fourmilière + Radar + cohérence)", "admin_donnees",
    "/admin/flux + /admin/flux/runs", "json_puis_js", chiffres=("n_sources", "n_sources_surveillees", "run_label_servi",)),
 "admin_mise_a_jour": _r("admin", "Données › Mise à jour (Injecter·Calculer·Basculer)", "admin_donnees",
    "/admin/flux/run/lancer + /admin/flux/bascule", "json_puis_js", chiffres=("ecart_candidat_pct",)),
 "admin_produit": _r("admin", "Données produit (usage outils + retours)", "admin_donnees",
    "/admin/produit", "json_puis_js", chiffres=("usage_outil_n",)),
 "admin_ia": _r("admin", "IA & quotas Copilote", None,
    "/admin/ia", "json_puis_js", chiffres=("ia_cout_eur",)),
 "admin_radar": _r("admin", "Radar (dépôts à vérifier)", None,
    "/admin/radar/*", "json_puis_js", chiffres=("n_depots_a_verifier",)),
 "admin_destinations": _r("admin", "Destinations (calibration PLU)", None,
    "/admin/destinations", "json_puis_js", chiffres=("n_communes_rnu",)),
 "admin_licences": _r("admin", "Licences (comptes, essais, quotas)", None,
    "/admin/licences", "json_puis_js", chiffres=("n_comptes_actifs",)), # ── CIRCUIT-1 lot 2.1 — le sélecteur de zones du panneau de filtres (compte, jamais une part) ──
 "panel_filtres": _r("outil", "Filtres (sélecteur de zones PLU)", None,
    "/zonage/zones", "json_puis_js", chiffres=("parcelles_par_zone_n",)),
}
