-- M6 Phase 2a P1 (13/07/2026) — ROLLBACK — restaure les legal_notes d'avant le 2a-p1 data_sources (audit 1-11)
BEGIN;
UPDATE data_sources SET legal_notes = 'Parcellaire Express (PCI), MAJ semestrielle ; BD Parcellaire gelée depuis 2019.', updated_at = now() WHERE name = 'Cadastre (API Carto PCI)';
UPDATE data_sources SET legal_notes = NULL, updated_at = now() WHERE name = 'Cadastre Etalab (bulk DGFiP/Etalab)';
UPDATE data_sources SET legal_notes = NULL, updated_at = now() WHERE name = 'Urbanisme PLU/GPU (API Carto)';
UPDATE data_sources SET legal_notes = NULL, updated_at = now() WHERE name = 'Géorisques';
UPDATE data_sources SET legal_notes = 'R112 A-3 LPF : interdiction de réidentifier / d''indexer. Agréger, jamais nominatif.', updated_at = now() WHERE name = 'DVF / valeurs foncières';
UPDATE data_sources SET legal_notes = NULL, updated_at = now() WHERE name = 'RGE ALTI (altimétrie)';
UPDATE data_sources SET legal_notes = NULL, updated_at = now() WHERE name = 'Parc National de La Réunion (INPN)';
UPDATE data_sources SET legal_notes = NULL, updated_at = now() WHERE name = 'Forêts publiques (ONF)';
UPDATE data_sources SET legal_notes = 'SAR juridiquement SUPÉRIEUR au PLU.', updated_at = now() WHERE name = 'SAR Réunion (PEIGEO)';
UPDATE data_sources SET legal_notes = 'Droit de préemption SAFER.', updated_at = now() WHERE name = 'Zonage SAFER (DAAF)';
UPDATE data_sources SET legal_notes = NULL, updated_at = now() WHERE name = 'Région Réunion Open Data (Opendatasoft)';
UPDATE data_sources SET legal_notes = NULL, updated_at = now() WHERE name = 'PEIGEO (hub régional)';
UPDATE data_sources SET legal_notes = NULL, updated_at = now() WHERE name = 'DEAL Réunion (WMS/WFS)';
UPDATE data_sources SET legal_notes = NULL, updated_at = now() WHERE name = 'Géoplateforme IGN';
UPDATE data_sources SET legal_notes = NULL, updated_at = now() WHERE name = 'data.regionreunion.com — Potentiel foncier';
UPDATE data_sources SET legal_notes = 'Licence Ouverte. Pétitionnaires personnes MORALES seulement (physiques anonymisées à la source).', updated_at = now() WHERE name = 'SITADEL (autorisations d''urbanisme)';
UPDATE data_sources SET legal_notes = NULL, updated_at = now() WHERE name = 'BD TOPO IGN';
UPDATE data_sources SET legal_notes = NULL, updated_at = now() WHERE name = 'Base Adresse Nationale';
UPDATE data_sources SET legal_notes = 'Signal complémentaire, JAMAIS vérité juridique.', updated_at = now() WHERE name = 'OpenStreetMap / Overpass';
UPDATE data_sources SET legal_notes = NULL, updated_at = now() WHERE name = 'BPE INSEE';
UPDATE data_sources SET legal_notes = NULL, updated_at = now() WHERE name = 'SIRENE';
UPDATE data_sources SET legal_notes = NULL, updated_at = now() WHERE name = 'OCS GE (IGN)';
UPDATE data_sources SET legal_notes = NULL, updated_at = now() WHERE name = 'ZNIEFF (INPN / Région)';
UPDATE data_sources SET legal_notes = NULL, updated_at = now() WHERE name = 'ABF / Monuments historiques';
UPDATE data_sources SET legal_notes = 'Droit de préemption départemental.', updated_at = now() WHERE name = 'ENS (Département)';
UPDATE data_sources SET legal_notes = NULL, updated_at = now() WHERE name = 'VRD / assainissement (SPANC)';
UPDATE data_sources SET legal_notes = 'Accès sous convention. Version anonymisée : physiques masquées (_X_), morales complètes → RGPD-safe.', updated_at = now() WHERE name = 'Fichiers fonciers (Cerema)';
UPDATE data_sources SET legal_notes = NULL, updated_at = now() WHERE name = 'DEAL Réunion — trait de côte';
UPDATE data_sources SET legal_notes = 'Licence Ouverte v2.0 — paternité DILA. RGPD : signal INTERNE de priorisation (personnes morales, open data), jamais un export nominatif de masse (règle d''archi #2).', updated_at = now() WHERE name = 'BODACC (procédures collectives)';
UPDATE data_sources SET legal_notes = NULL, updated_at = now() WHERE name = 'DEAL Réunion — PPR / aléas';
UPDATE data_sources SET legal_notes = 'RGPD : personnes morales en open data complet ; données d''une personne PHYSIQUE conservées seulement si l''entreprise est diffusible. Signal INTERNE de priorisation, jamais un export nominatif de masse (règle d''archi #2). Naissance au MOIS.', updated_at = now() WHERE name = 'INPI RNE (dirigeants)';
UPDATE data_sources SET legal_notes = NULL, updated_at = now() WHERE name = 'Géorisques — sites et sols pollués';
UPDATE data_sources SET legal_notes = NULL, updated_at = now() WHERE name = 'Géorisques — cavités souterraines';
UPDATE data_sources SET legal_notes = NULL, updated_at = now() WHERE name = 'Géorisques — ICPE';
UPDATE data_sources SET legal_notes = 'Licence ouverte 2.0. MAJ trimestrielle.', updated_at = now() WHERE name = 'Cartofriches (Cerema)';
UPDATE data_sources SET legal_notes = NULL, updated_at = now() WHERE name = 'Géorisques — mouvements de terrain';
UPDATE data_sources SET legal_notes = 'Licence ouverte. RGPD : diagnostic du bien, pas nominatif.', updated_at = now() WHERE name = 'DPE ADEME (logements existants)';
UPDATE data_sources SET legal_notes = 'Licence ouverte. Décret 2023-1314 (génération 2024, en vigueur 01/01/2024).', updated_at = now() WHERE name = 'QPV 2024 (ANCT)';
UPDATE data_sources SET legal_notes = 'Licence Ouverte (GPU). Assiettes telles que téléversées par les gestionnaires — exhaustivité variable par catégorie.', updated_at = now() WHERE name = 'SUP — assiettes GPU (API Carto)';
UPDATE data_sources SET legal_notes = 'Open data DINUM (agrégat INSEE/RNE). RGPD : personnes morales ; signal INTERNE de priorisation (Score V), jamais un export nominatif de masse (règle d''archi #2).', updated_at = now() WHERE name = 'Recherche d''entreprises (DINUM)';
UPDATE data_sources SET legal_notes = 'Open data Cerema. Classement en vigueur : arrêtés préfectoraux 14-15/12/2023.', updated_at = now() WHERE name = 'Classement sonore ITT (Cerema)';
UPDATE data_sources SET legal_notes = 'Limite numérisée du cadastre 1877 (géoréf. orthos 2012/1950) — indicative, la bande polygonale officielle n''est pas diffusée.', updated_at = now() WHERE name = '50 pas géométriques — limite haute (DEAL)';
UPDATE data_sources SET legal_notes = 'Gratuit, sans clé, réutilisation et stockage libres (données CE).', updated_at = now() WHERE name = 'PVGIS (Commission européenne)';
UPDATE data_sources SET legal_notes = 'Licence Ouverte (jeux publiés par EDF SEI, ZNI).', updated_at = now() WHERE name = 'EDF SEI Réunion — open data';
UPDATE data_sources SET legal_notes = 'Licence Ouverte. Installations ≥ 36 kVA individualisées, petites agrégées par commune.', updated_at = now() WHERE name = 'Registre national des installations (ODRÉ)';
UPDATE data_sources SET legal_notes = 'ODbL — attribution OSM.', updated_at = now() WHERE name = 'Parkings OSM (loi APER)';
DELETE FROM data_sources WHERE name = 'Filosofi INSEE (carreaux 200 m)';
COMMIT;
