import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1280, height: 1100 } })
await p.goto('http://localhost:5173/socle/', { waitUntil: 'domcontentloaded' })
await p.waitForSelector('nav button')
await p.evaluate(() => localStorage.clear())
await p.click('nav button:has-text("Copilote")')
await p.waitForSelector('[data-copilote]')
await p.fill('[data-brief]', 'Terrain pour un collectif de 8 logements à Saint-Pierre, budget 600 k€')
await p.click('[data-instruire]')
await p.waitForSelector('[data-quota-panel], [data-en-cours], [data-fil]', { timeout: 20000 })
const quota = await p.locator('[data-quota-panel]').count()
await p.waitForTimeout(400)
await p.screenshot({ path: 'qa/captures/m26c-etat5-quota.png' })
console.log('quota panel:', quota > 0, '—', quota > 0 ? (await p.locator('[data-quota-detail]').textContent())?.trim() : 'RUN CRÉÉ (pas de 429)')
await b.close()
