import { chromium } from 'playwright'
const OUT = '../../reports/pre-lancement/captures'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 430, height: 1000 } })
await p.goto('http://127.0.0.1:8010/socle/', { waitUntil: 'networkidle' })
await p.waitForFunction(() => window.__labuse && window.__labuse.setModule, { timeout: 10000 })
await p.evaluate(() => window.__labuse.setCommune('Saint-Paul'))
await p.evaluate(() => window.__labuse.setModule('matching'))
await p.waitForSelector('[data-m19-idu]', { timeout: 8000 })
await p.locator('[data-m19-idu]').fill('97415000DK1169')
await p.waitForSelector('[data-m19-compat]', { timeout: 8000 })
await p.waitForSelector('[data-m19-actifs]', { timeout: 8000 })
await p.waitForTimeout(1000)
const body = await p.evaluate(() => document.body.innerText)
console.log('compat démo présent:', body.includes('/100'))
console.log('promoteurs réels SITADEL:', body.includes('RÉEL · SITADEL'))
console.log('démo labellisé:', body.includes('DÉMO · ILLUSTRATIF'))
console.log('SIREN affiché (PM):', /SIREN \d/.test(body))
await p.screenshot({ path: `${OUT}/matching-plus.png` })
await b.close(); console.log('matching capture OK')
