import { chromium } from 'playwright'
const OUT = '../../reports/pre-lancement/captures'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 430, height: 950 } })
await p.goto('http://127.0.0.1:8010/socle/', { waitUntil: 'networkidle' })
await p.waitForFunction(() => window.__labuse && window.__labuse.setModule, { timeout: 10000 })
await p.evaluate(() => window.__labuse.setModule('zan'))
await p.waitForSelector('[data-zan-idu]', { timeout: 8000 })
// cas CONTRAINTE + EXEMPTION SRU (agricole + AU + Saint-Leu carencée)
await p.locator('[data-zan-idu]').fill('97413000DG1036')
await p.waitForSelector('[data-zan-signal]', { timeout: 8000 })
await p.waitForTimeout(1200)
console.log('signal contrainte:', (await p.locator('[data-zan-signal]').innerText()).replace(/\s+/g,' ').slice(0,140))
await p.screenshot({ path: `${OUT}/zan-contrainte-exemption.png` })
// cas ALIGNÉ (artificialisé + zone U)
await p.locator('[data-zan-idu]').fill('97413000AV1502')
await p.waitForTimeout(1500)
console.log('signal aligne:', (await p.locator('[data-zan-signal]').innerText()).replace(/\s+/g,' ').slice(0,120))
await p.screenshot({ path: `${OUT}/zan-aligne.png` })
await b.close(); console.log('zan captures OK')
